### PR TITLE
Update migration-interop-guidance-for-teams-with-skype.md

### PR DESCRIPTION
**Pull request by bjwhalen**
remove TAP disclaimer about MMS and add clarification around MMS.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Merged without copy review.

**Comment by tonysmit** [comment]
@CarolynRowe  - the urls listed must have en-us removed from them. Thanks.

**Comment by CarolynRowe** [comment]
This is fixed.  Will go live tonight.

**Pull request merged**
