### PR TITLE
Liceinsing for Compliance Content Search

### PR DESCRIPTION
**Pull request by naminakao**
Based on the following public content, Compliance Content Search (eDiscovery Search) is available with O365 Business Premium and Enterprise E1.

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-business-and-enterprise-plans

### CODE REVIEW

**Comment by kenwith** [comment]
@LolaJacobsen - OK to merge?

**Comment by kenwith** [comment]
@anach - I noticed you are listed as ms.reviewer in metadata. Is this OK to merge? It has been open 27 days.

**Comment by scanum** [comment]
@LolaJacobsen can this be merged?

**Comment by kenwith** [comment]
@naminakao  and @scanum -- I reviewed the reference document and agree it is saying that ediscovery search is included in these licenses. This change looks good to me. I am covering for Lola so will go ahead and merge this.

**Pull request merged**
