### PR TITLE
Update set-the-caller-id-for-a-user.md

### PR DESCRIPTION
**Pull request by shashank1320**
Please merge the changes to have accurate and precise information rather than just addition of lines.

### CODE REVIEW

**Comment by shashank1320** [comment]
Please merge the changes.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by shashank1320 — COMMENTED** [review]
Good to publish.

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
