### PR TITLE
Update toll-free-dialing-restrictions-in-egypt.md

### PR DESCRIPTION
**Pull request by ruizoscar**
Correcting information.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
@scanum Hi Manuela, I merged this PR, but FYI, @v-cichur is handling all the PRs for updates to the availability topics.  So, FYI, for future requests.  Thanks!

**Comment by CarolynRowe** [comment]
That's @cichur...

**Pull request merged**
