### PR TITLE
Update availability-in-germany.md

### PR DESCRIPTION
**Pull request by ErsancMS**
Right value should be Munich, not Frnakfurt

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by ErsancMS** [comment]
@CarolynRowe can you please help us push this PR?

**Comment by CarolynRowe** [comment]
I need to check with the availability PMs.  They are the only ones with authority to change content in these documents.  I've followed up with them.

**Comment by CarolynRowe** [comment]
This PR was handled in a separate update so I am closing this PR.  The following changes should go live today:
- Are phone numbers automatically assigned for Audio Conferencing - Changed to Munich
- What capitals or major cities can you get toll numbers for - Changed to Frankfurt and Munich

**Pull request closed without merging**
