### PR TITLE
Update guest licenses required for paid AAD features in guest-access.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5179.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChinPR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@somakbhattacharyya please review this PR and let us know whether it's OK to merge.

**Comment by somakbhattacharyya** [comment]
Approved.

**Pull request merged**
