### PR TITLE
Update plan-for-teams-live-events.md

### PR DESCRIPTION
**Pull request by lcansby**
Live Events produced in Teams now supports 16 hours.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by LolaJacobsen** [comment]
@LanaChin we did a different update to address this issue. I'm closing this one.

**Pull request closed without merging**
