### PR TITLE
Update teams-exploratory.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3616

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@Balu-msft  - please review. LMK if it's OK to merge.

**Comment by dariomws** [comment]
@Balu-msft thank you for your feedback.

Good information. I verified in an E5 it still says "Flow for Office 365" too. So let's put the image and then it should be updated when it's renamed in the Admin Center.

Thanks again!

**Pull request closed without merging**
