### PR TITLE
SEO Edits rooms-index

### PR DESCRIPTION
**Pull request by jdmartinez36**
SEO edits to the Teams Rooms landing page. Edited title and description by adding keywords. Instead of creating new content to include collaboration bar, included it as an example in the sentence regarding audio video peripherals.

Per the SEO findings, a search for "custom themes" is associated with this page. Custom themes instructions are located at https://docs.microsoft.com/en-us/microsoftteams/rooms/xml-config-file, found in the left-hand nav pane under Manage. It's likely difficult to find since the title is "Manage a Microsoft Teams Rooms console settings remotely with an XML configuration file".

A possible option is adding a sentence at the end of the landing page, "If you're looking for information to create custom themes for your Teams Room, see <link>." It would pretty much act as an addendum, and it could help since we know this is something customers are searching for when they end up on this page.

### CODE REVIEW

**Comment by jdmartinez36** [comment]
@DaniHalfin

**Comment by DaniHalfin** [comment]
I'm reviewing. Thanks.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@LanaChin & @dstrome Please review the proposed title change. I'm not sure it's accurate...

**Pull request merged**
