### PR TITLE
Update msi-deployment.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #2089 - Command has been corrected now.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@voltarone @juturu OK to merge?

**Comment by LolaJacobsen** [comment]
I pinged the 2 PMs again - @voltarone @juturu

**Comment by scanum** [comment]
@Lester-Hewett Hi Lester, could you please review this Pr and merge if correct. Thanks!

**Comment by jambirk** [comment]
@scanum  Lester has moved on. Please let @LolaJacobsen follow up with the needed PMs

**Pull request merged**
