### PR TITLE
Update list

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7998

source 
image
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-september-2021/ba-p/2793627

@HowlinWolf-92 please review

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@SerdarSoysal  Can you help me getting merged this ? Thank you

**Comment by get-itips** [comment]
@tiburd or @SerdarSoysal can help me review and merge this? thank you

**Comment by tiburd** [comment]
reviewed + confirmed

**Pull request merged**
