### PR TITLE
Update user-activity-report.md

### PR DESCRIPTION
**Pull request by dipinn26592**
Customers are confused if we only shows unplanned meeting number or if we show the planned number as well.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
Hi @dstrome Wondering if you can help with this PR? Thanks.

**Comment by scanum** [comment]
Hi @dstrome Wondering if you can help with this PR? Thanks.

**Pull request closed without merging**
