### PR TITLE
http://SkypeandTeams.com Not Working

### PR DESCRIPTION
**Pull request by dplotnikov**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2653

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@dearbeen - please review. Where do you want this link to go instead of http://skypeandteams.com?

**Comment by LolaJacobsen** [comment]
We're deprecating this topic, so I'll close without merging.

**Pull request closed without merging**
