### PR TITLE
Add troubleshooting section to teams-standalone-static-tabs-using-spo-sites.md

### PR DESCRIPTION
**Pull request by dariomws**
Replaces https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6994. Please merge it without tag reviewers as we did it in PR 6994.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MicrosoftHeidi** [comment]
We don't typically put troubleshooting guides into our content, I will have to locate and discuss with the PM owner, as troubleshooting should go into a separate article (following intent) that's managed by a different team.

**Comment by dariomws** [comment]
@MicrosoftHeidi In that case, I think this PR can be closed. It's not critical information.

**Comment by tiburd** [comment]
Closing this PR.

cc: @scanum

**Pull request closed without merging**
