### PR TITLE
Admin center name is wrong #1776 

### PR DESCRIPTION
**Pull request by sukihanabi**
#1776 admin center name is wrong

### CODE REVIEW

**Comment by sukihanabi** [comment]
#1791  How do you assign an emergency location via powershell?

**Comment by scanum** [comment]
@tonysmit Hi Tony, could you please take a look to confirm the changes @sukihanabi made. These look correct, could you please confirm and merge? Thanks!

**Comment by sukihanabi** [comment]
> #1776 admin center name is wrong

**Comment by sukihanabi** [comment]
#1782 Change bold font to contact email support 

The answer to user question might not be available to the public because for the devices to be certified and be part of SBC, MS needs to perform an intense test.  But it was indicated on the article: " If you have any questions about SBC certification program for Direct Routing please email to drsbccertification@microsoft.com" Can we instead direct the user to email the support or perhaps a uservoice? Related Uservoice: https://www.skypefeedback.com/forums/299910-recently-released/suggestions/13732851-expand-skype-certified-devices.

**Comment by sukihanabi** [comment]
#1830 Changes made to plan-for-teams-live-events

**Comment by sukihanabi** [comment]
#1820 Pay per minute Charge

>Created "Why is it best for you?" and provided all necessary advantages of purchasing Audio Conferencing pay-per-minute licenses, including 
answer to inquiry #1820  , that pay per minutes is not being charge for the conference line nor pay per minute times 5 participants."
It is being charge by each attendee attends the meeting via phone call instead of SFB/ Team Application, vary rates vary for toll or toll-free call and by destination."

### **Watched and read the references below to come-up with the resolution:**
**Article**
Try or purchase Audio Conferencing in Office 365 for Skype for Business Online
https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/try-or-purchase-audio-conferencing-in-office-365

Audio Conferencing extended to Microsoft Team and pay-per-minute offering added for more options
https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Audio-Conferencing-extended-to-Microsoft-Team-and-pay-per-minute/ba-p/110936

**Youtube:**
SfB Broadcast: Ep. 50 What's new with PSTN Conferencing
https://www.youtube.com/watch?v=bcbE9JSUZ_Y&index=4&list=PLx28OnnzHAl2RTtyPdpFnJRwTsMZpgqC-&t=16s

SfB Broadcast: Ep. 42 Configuring PSTN Consumption Billing in O365
https://www.youtube.com/watch?v=wDEjoRG2zeY&t=1s

**Comment by sukihanabi** [comment]
#1790 Billing clarification for EA customers
_The answer to the customer inquiry is:_
With Communication Credits, monthly billing depends on their allotted fund usage(metered billing). if for example customer was not able to use it. they still have 12 months before it get's forfeited. 

_Already written in the article._
"Funds will be applied only to Communications Credits at Microsoft published rates when the services are used. Any funds not used within 12 months of the purchase date will expire and be forfeited."

_Action Taken:_
-Previous link is not working, added the correct the link:
[Skype for Business PSTN usage report](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online-reporting/pstn-usage-report)
-Added and clarify the monthly billing- "Monthly billing for Communication Credits will only be applied if the alloted fund has been used, to check on your monthly usage we recommend to view"

_References:_ 
SfB Broadcast: Ep. 42 Configuring PSTN Consumption Billing in O365 (now it is called Communications Credits )
At 19:59 = EA, discussed about Enterprise Agreement Customer, already written in the article. "Set up Communications Credits for your organization"
https://www.youtube.com/watch?v=wDEjoRG2zeY&list=PLx28OnnzHAl2RTtyPdpFnJRwTsMZpgqC-&index=2

What is communication credit
https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits?toc=/skypeforbusiness/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json

**Comment by sukihanabi** [comment]
_Action Taken:_
Added Bullet
"- Control and protect the configuration of compliance policies in Teams and Exchange using Conditional Access. "
and links for the ff: [How do Conditional Access policies work for Teams?](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#how-do-conditional-access-policies-work-for-teams) and [Set up app-based conditional access policies with Intune](https://docs.microsoft.com/en-us/intune/app-based-conditional-access-intune-create)
_ #References:_
Conditional Access in Outlook on the web for Exchange Online
https://techcommunity.microsoft.com/t5/Outlook-Blog/Conditional-Access-in-Outlook-on-the-web-for-Exchange-Online/ba-p/267069

Reference article https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview#how-do-conditional-access-policies-work-for-teams

Set up app-based conditional access policies with Intune
https://docs.microsoft.com/en-us/intune/app-based-conditional-access-intune-create

What is conditional access in Azure Active Directory?
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview

How to create and assign app protection policies
https://docs.microsoft.com/en-us/intune/app-protection-policies

Azure Active Directory conditional access settings reference
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/technical-reference#feedback

**Comment by sukihanabi** [comment]
#1789 Add note under conferencing support that viewing embedded video in PPT isn't supported. 
Action Taken:
* Added #3 to IOS and Android under "View shared PowerPoint files" with a note that states, "Viewing embedded video in PowerPoint presentations is not supported."

See UserVoice:
Verbatim: "The ios Skype for business client (Phone and ipad) does not play videos embedded in PowerPoint. This has been confirmed by Microsoft support"
https://www.skypefeedback.com/forums/299913-generally-available/suggestions/31537219-the-ios-skype-for-business-client-phone-and-ipad

https://www.skypefeedback.com/forums/299913-generally-available/suggestions/35314720-powerpoint-sharing-error-in-android-app

**Comment by kenwith** [comment]
@sukihanabi - please open only one PR per Issue and per Article so it is manageable to get approval and merge. CC @scanum

**Pull request closed without merging**
