### PR TITLE
Reassigning authorship

### PR DESCRIPTION
**Pull request by mattpennathe3rd**
@msdmaguire A happy day to you. Apparently, there were many files in this repo assigned to me (which somehow I did not know about), so this PR reassigns all of my files to you.

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5540 and some others have tagged me because I am still listed as the author.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — COMMENTED** [review]
No copy to review.

**Comment by scanum** [comment]
Hi @mattpennathe3rd hope you are doing well. You will have to sign the CLA. Thank you!

**Comment by mattpennathe3rd** [comment]
@scanum Sorry about that. It should be all set, now. I miss you all and I hope things are going well.

**Comment by scanum** [comment]
@mattpennathe3rd No worries, thank you so much! We miss you as well. Hope everything is alright and you are staying safe!

**Comment by scanum** [comment]
@msdmaguire PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
