### PR TITLE
Updated private channel sites visibility in SPO Admin Center (private-channels.md)

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3361.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Reached out to PM for confirmation.

**Comment by dariomws** [comment]
@LanaChin I tested it, and now we can see private channel sites in the SPO Admin Center.

**Comment by LanaChin** [comment]
Thanks @dariomws. Per the PM, a change was made and private channel sites are no longer visible in the SharePoint admin center. No changes needed at this time.

**Pull request closed without merging**
