### PR TITLE
Update system-requirements.md

### PR DESCRIPTION
**Pull request by hirenshah1**
Updated the documentation from New Control Panel of SFB Server 2019 CU1. The changes need to be enabled along with GA of CU1

### CODE REVIEW

**Comment by hirenshah1** [comment]
@jamtur01 , Please review and approve

**Comment by jamtur01** [comment]
@hirenshah1 Are you sure you meant me?

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by hirenshah1** [comment]
> @hirenshah1 Are you sure you meant me?
I am PM for Skype for Business but I do not have the write access to these documents. 
Also, I have worked with Heidi a bit, but not sure if she handles all the documentation for SFB.
Any pointers in this regards will be helpful. Thank you !

**Comment by scanum** [comment]
@hirenshah1 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by hirenshah1** [comment]
I cannot merge files as I do not have write access. @JohanFreelancer9 please merge these changes to main document.

**Comment by JohanFreelancer9** [comment]
@hirenshah1 I do not have rights to merge.

**Comment by jamtur01** [comment]
@hirenshah1 I think you need to check on who is the right participant. I do not work on this project.

**Comment by hirenshah1** [comment]
@chrisda or @kenwith , can you please approve the changes. This change is needed for recently released SFB Server 2019 CU1

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by hirenshah1** [comment]
Thank you @scanum for your help. @MicrosoftHeidi , please check and merge. 
Appreciate all your support.

**Pull request merged**
