### PR TITLE
Added note about mailbox needed

### PR DESCRIPTION
**Pull request by get-itips**
Added note about mailbox needed https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1404

### CODE REVIEW

**Comment by scanum** [comment]
@tonysmit Hi Tony, changes look correct. Could you please take a look and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@LanaChin please verify & merge this PR.

**Comment by LolaJacobsen** [comment]
@LanaChin is getting tech review from program manager s one.

**Comment by LanaChin** [comment]
Awaiting review by PM.

**Comment by scanum** [comment]
@LanaChin Hi Lana, any updates on this? Thanks!

**Comment by LanaChin** [comment]
Confirmed and merged.

**Pull request merged**
