### PR TITLE
Update direct-routing-plan.md

### PR DESCRIPTION
**Pull request by revaldiv**
Added Important note at line 97-98 to be sure AC licenses are disabled for GCCH/DOD customers until user provisioning has completed and they have a working dial pad per ICM 221800930

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review.

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by JohanFreelancer9** [comment]
@revaldiv - could you please commit my changes. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request merged**
