### PR TITLE
Added information to note (create-a-phone-system-call-queue.md)

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7888.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@CLYVR can you review?

**Review by CLYVR — CHANGES_REQUESTED** [review]
@MikePlumleyMSFT 
Suggest the following:
All routing methods will route calls to agents if their presence is available.

But not clear on the actual need for a change - have there been questions or feedback on the original statement?

**Comment by dariomws** [comment]
@CLYVR @MikePlumleyMSFT thank you for your help.

There was feedback about the original statement:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7888
It seems that he is a Microsoft employee.

**Comment by MikePlumleyMSFT** [comment]
@CLYVR if it's only the case that calls are routed to agents with an available status, then I agree - not sure we need a change. @alfimasing please contact us internally if you feel there's confusion here and an update is needed.

**Comment by alfimasing** [comment]
OK I'll do that...

Viele Grüße / Best Regards
Alfred Masing
Technical Specialist | Germany | +49 89 3174 3499<tel:+498931743499> | +49 151 58956349<tel:+4915158956349>
***@***.******@***.***>  |   ***@***.***  ***@***.***>
***@***.***

Von: Mike Plumley ***@***.***>
Gesendet: Freitag, 1. Oktober 2021 23:06
An: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Alfred Masing ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Added information to note (create-a-phone-system-call-queue.md) (#7912)


@CLYVR<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCLYVR&data=04%7C01%7Camasing%40microsoft.com%7Cfab75648f83d49a92a2008d9851f43bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637687191619282238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vmht0j%2Br72Z65Zzr%2FukJMl2ypvqu0XRejDw5QXHCE%2Fk%3D&reserved=0> if it's only the case that calls are routed to agents with an available status, then I agree - not sure we need a change. @alfimasing<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falfimasing&data=04%7C01%7Camasing%40microsoft.com%7Cfab75648f83d49a92a2008d9851f43bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637687191619282238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QBOeiH3TYQ1M5ATB5wjRb6veUfm5Zl%2BnOcpRhZd3FzI%3D&reserved=0> please contact us internally if you feel there's confusion here and an update is needed.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F7912%23issuecomment-932565219&data=04%7C01%7Camasing%40microsoft.com%7Cfab75648f83d49a92a2008d9851f43bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637687191619282238%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2QgCeyQnRe8VnK4OQv6yW2COghkqTFNx%2B2V7CLpTLO4%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVCWCNLCL7HM73INMFD3K53UEYPDLANCNFSM5E3SO24A&data=04%7C01%7Camasing%40microsoft.com%7Cfab75648f83d49a92a2008d9851f43bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637687191619292193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=efP3nCAFGzy77jrETBYNy6ppGRn%2FBvOaP7IImWApLW8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Camasing%40microsoft.com%7Cfab75648f83d49a92a2008d9851f43bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637687191619292193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UG0qXCWN5Fzr9TsZOqBue6Orlh5MOUl3OGX6QDpYGWs%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Camasing%40microsoft.com%7Cfab75648f83d49a92a2008d9851f43bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637687191619302152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zWx9AHbHccMkHlRgzJhKxPWRPEogTC2ZTQm%2B7kfuKuM%3D&reserved=0>.

**Pull request closed without merging**
