### PR TITLE
Add note about GCCH and DoD to direct-routing-connect-the-sbc.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9630.

@bradbrill, if you want to review it. Thanks!

### CODE REVIEW

**Comment by bradbrill** [comment]
The note looks great

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@FilippSe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@FilippSe
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by FilippSe — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
