### PR TITLE
Replace author (cichur - mahoffman)

### PR DESCRIPTION
**Pull request by dariomws**
Replace cichur with mahoffman.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@traya1 
Hi,
I assigned this PR to you because it includes more than 100 files. 
Let me know if I should proceed differently.
Thanks!

**Comment by traya1** [comment]
Sorry for the delayed response. I am closing the PR as PRs with 100+ changed files are not allowed in public repos.

Regarding the nature of the proposed updates, we are updating the metadata values internally and these changes should reflect in the public repo soon.

**Pull request closed without merging**
