### PR TITLE
Added Vietnam to 'no toll number' countries

### PR DESCRIPTION
**Pull request by robdy**
Looks like settings for [Vietnam](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-vietnam) are same as [for UAE](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-the-united-arab-emirates-uae) but the former is not listed in the note:

> Due to limited availability of toll phone numbers in Venezuela, Indonesia, and United Arab Emirates (UAE), organizations from these countries/regions won't have an Audio Conferencing toll number automatically assigned to them. Toll-free numbers from these locations are available depending on available inventory

Therefore, I added Vietnam to the list

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmit changes look correct. Could you please confirm and merge? Thanks!

**Comment by scanum** [comment]
@tonysmit Changes look correct. Could you please review and merge? Thanks!

**Comment by tonysmit** [comment]
@ruizoscar or @msmikedavis - Can either of you confirm this change please? If it's correct, I will merge it.

**Comment by ruizoscar** [comment]
The change looks good, let's move forward with it. Thank you!

**Comment by ruizoscar** [comment]
Hi @Tony<mailto:Tony.Smith@microsoft.com>, just replied on GitHub, the change looks good. Thanks for checking!

**Pull request merged**
