### PR TITLE
Update live-events-recording-policies.md

### PR DESCRIPTION
**Pull request by bartvermeersch**
Adding 180-day period download availability for producers and presenters.

### CODE REVIEW

**Comment by bartvermeersch** [comment]
See https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7892

**Comment by lindspea** [comment]
Looks good thanks @bartvermeersch. Once the author approves and merges, it will go live. Thanks again for your help.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
