### PR TITLE
Fix issue #5914

### PR DESCRIPTION
**Pull request by davideferre**
Fix typo #hacktoberfest2020

### CODE REVIEW

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by davideferre** [comment]
@scanum @JohanFreelancer9 can you please add the label `hacktoberfest-accepted` to this PR?

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
