### PR TITLE
Update limits-specifications-teams.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5748
Added link for more info.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by SerdarSoysal** [comment]
I don't think this PR addresses the issue. The issue was that there was conflicting limits in the two articles. Let me investigate.

**Comment by cichur** [comment]
I've fixed the Live Events article to include the 180-day limit for retaining recordings. The changes will be live this afternoon.

**Pull request merged**
