### PR TITLE
Adding automatic conv from open to implicit

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8122

@robmazz Robert, please review. I could verify this in my lab tenant. Thank you

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@robmazz PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@tiburd Can you help me get this merged? Thank you

**Comment by get-itips** [comment]
replacing with another PR because of file conflict

**Pull request closed without merging**
