### PR TITLE
SEO edits quick-start-meetings-live-events

### PR DESCRIPTION
**Pull request by jdmartinez36**
Edited title and description to use search keywords recommended by SEO expert. Added "online" and "video" where appropriate. Added video conferencing to licensing paragraph for SEO.

For review by Dani Halfin

### CODE REVIEW

**Comment by jdmartinez36** [comment]
@DaniHalfin

**Comment by scanum** [comment]
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by DaniHalfin** [comment]
I'm reviewing. Thanks.

**Comment by scanum** [comment]
@DaniHalfin Hi! Is this PR going to be closed? Thanks!

**Comment by jdmartinez36** [comment]
@LolaJacobsen 
Let me know what you think of this description. I can also pull out the licenses part, just trying to add it for SEO.

**Pull request merged**
