### PR TITLE
Update virtual-user.md

### PR DESCRIPTION
**Pull request by revaldiv**
@line 50 revised the Note to state the Preview Mode in the Admin Portal should be off.  I had a customer report issue finding the license when following the prior guidance.  I confirmed we only see the license when Preview Mode is OFF.  Not sure how we want to word this - but needs to reflect that navigating in Preview Mode of the Admin Portal doesn't show the license option so users need to turn it off if they have it on.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@jambirk PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by jambirk** [comment]
@scanum If the assertion is correct, the best solution is to remove the note entirely.  

@waseemhashem do you agree?

**Comment by scanum** [comment]
@jambirk I can have a freelancer remove this note. Should we wait until @waseemhashem agrees with this decision? Thanks!

**Comment by lindspea** [comment]
#3103

**Comment by jambirk** [comment]
I would say Yes, this needs approval from @waseemhashem  .

**Comment by revaldiv** [comment]
I agree that Waseem should approve.

However, I do not think the note should be removed because then we will get support tickets when customer’s cannot find the virtual license when they are in the new admin center…..



Rebecca I Valdivia

Microsoft Corporation | Support Escalation Engineer | Microsoft Teams
IM: revaldiv@microsoft.com<mailto:revaldiv@microsoft.com>      Office: +1-469-775-3140
http://premier.microsoft.com<http://premier.microsoft.com/>
Time zone: (UTC-08:00) Pacific Time (US and Canada), 9.00am – 6.00pm
Escalation Manager: Rishender Taneja rtaneja@microsoft.com<mailto:rtaneja@microsoft.com>, +1-425-706-5773
[cid:image003.png@01D57782.D9F98580]

**Comment by jambirk** [comment]
@waseemhashem Please review this proposed change and indicate whether or not to move forward. Personally, I think removing the note entirely might be a better solution than inverting the recommendation. need ot hear from you before acting.

**Comment by waseemhashem** [comment]
@jambirk I think its better to invert it, people switch to the preview mode then get lost trying to find it. My devs keep getting lost there until now lol

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by lindspea** [comment]
Closes #3019

**Comment by lindspea** [comment]
#Closes 3019

**Comment by lindspea** [comment]
Resolves #3019

**Comment by lindspea** [comment]
@scanum can be closed thank you.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by lindspea** [comment]
@scanum please can you close this.

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by lindspea** [comment]
@scanum please can you close this one.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Pull request merged**
