### PR TITLE
update title and description

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6856

### CODE REVIEW

**Review by VLG17 — COMMENTED** [review]
removed too much from description

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
Hi @VLG17, I think this PR should be closed. These ARE admin features. I'm creating a new PR to fix what the issue author is asking.

Thank you!

**Pull request closed without merging**
