### PR TITLE
Update Known-issues.md

### PR DESCRIPTION
**Pull request by cowitkow**
SPO vanity domain issue resolved February 2019. https://icm.ad.msft.net/imp/v3/incidents/details/104609094/home

### CODE REVIEW

**Comment by LolaJacobsen** [comment]
@marclauinger needs to approve any changes to this article. Please do NOT merge this PR without his approval.

**Comment by marclauinger** [comment]
The ICM attached does not match the known issue.  The ICM is about adding a sharepoint tab and the Save button not getting activated, nothing about when going to the new tab it showing a blank page.  Has someone verified that adding an SPO page to a tab actually renders correctly now?

**Comment by cowitkow** [comment]
That should be relevant ICM that was holding up the actual deployment of the fix. This is also documented against https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/287249 and https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/243161. We can also defer to rajgopal@microsoft.com for this as needed.

**Comment by marclauinger** [comment]
Then it should be good.  I couldn't find the bugs and in the ICM I didn't see any links.  Approving.

**Pull request merged**
