### PR TITLE
Update content-camera.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3215
Changed authors as per @scanum

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@kenwith PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by kenwith** [comment]
The author should not have the @ sign so I will go ahead and adjust that now.

**Comment by kenwith** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3353

**Pull request merged**
