### PR TITLE
Multiple tenant data file performance, Fix Client-Client description

### PR DESCRIPTION
**Pull request by Rocheng**

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@Rocheng Please sign SLA, thanks for submitting feedback.

**Comment by scanum** [comment]
@Rocheng

**Comment by Rocheng** [comment]
I signed the CLA, please go ahead and complete the merge.  Thank you.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
Checking with PMs @williamlooney @GageAmes @msmikedavis

**Comment by LolaJacobsen** [comment]
OK to merge, per gagesames.

**Pull request merged**
