### PR TITLE
Update try-or-purchase-audio-conferencing-in-office-365.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed contradicting statement as we need communication credits to setup audio conferencing

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmit Changes look correct. Could you please review and merge? Thanks!

**Comment by tonysmit** [comment]
@ruizoscar or @msmikedavis  - Can you confirm that removing this statement is correct?

**Comment by ruizoscar** [comment]
Hi @Tony<mailto:Tony.Smith@microsoft.com>,

The edit is incorrect, (i) assigning communication credits licenses and (ii) setting up communication credits are two different things. For pay-per-minute, (i) is not required, but (ii) is.

A better edit could be:

To buy and assign pay-per-minute Audio Conferencing licenses:
If you're a Volume and Licensing customer, you can get pay-per-minute Audio Conferencing licenses. For additional information on pay-per-minute Audio Conferencing licenses, see Audio Conferencing pay-per-minute<https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute>.

  1.  Find out if Audio Conferencing is available in your country/region. Country and region availability for Audio Conferencing and Calling Plans<https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans>.
  2.  Get your Audio Conferencing licenses. To acquire pay-per-minute licenses, please contact your account representative.
  3.  Set up Communications Credits for your organization<https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization> for your organization by following “Step 2: Set up Communications Credits for your organization “ in Set up Communications Credits for your organization<https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization>. To learn more about Communication Credits, see What are Communications Credits?<https://docs.microsoft.com/en-us/microsoftteams/what-are-communications-credits>
Important: If Communications Credits haven't been set up, Audio Conferencing won't work for any users with pay-per-minute licenses. Also, if you have Audio Conferencing pay-per-minute licenses, you don't have to assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage (you might still need to assign them for other service

  1.  Assign or remove licenses for Office 365 for business<https://support.office.com/article/997596b5-4173-4627-b915-36abac6786dc> you purchased to the people in your organization who are going to schedule or lead meetings.
Thanks,
Oscar

**Comment by msbemba** [comment]
@ruizoscar @tonysmit Thank you for the suggestion. I'll work on the suggested changes and commit to this PR .

**Comment by tonysmit** [comment]
@msbemba - The big thing here is the Note that needs updated. In the email from Oscar above, you can't see the highlighted portions that need updated. So, I'm copy/pasting them from the email with Oscar for reference. And I proof read it and had minor changes. :) Make sure to change the Note to an Important.

**Text that needs updated**
3. Set up Communications Credits for your organization for your organization by following “Step 2: Set up Communications Credits for your organization“ in Set up Communications Credits for your organization. To learn more about Communication Credits, see What are Communications Credits?

**Important:** If Communications Credits haven't been set up, Audio Conferencing won't work for any users with pay-per-minute licenses. Also, if you have Audio Conferencing pay-per-minute licenses, you don't have to assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage but you might still need to assign them for another service.

**Comment by ruizoscar** [comment]
Awesome Oscar. Thanks for the updated text. That's super helpful.

From: Oscar Ruiz Garcia <Oscar.Ruiz@microsoft.com>
Sent: Thursday, June 6, 2019 9:07 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>; Tony Smith <Tony.Smith@microsoft.com>
Cc: Mike Davis <Mike.Davis@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update try-or-purchase-audio-conferencing-in-office-365.md (#2351)

Hi @Tony<mailto:Tony.Smith@microsoft.com>,

The edit is incorrect, (i) assigning communication credits licenses and (ii) setting up communication credits are two different things. For pay-per-minute, (i) is not required, but (ii) is.

A better edit could be:

To buy and assign pay-per-minute Audio Conferencing licenses:
If you're a Volume and Licensing customer, you can get pay-per-minute Audio Conferencing licenses. For additional information on pay-per-minute Audio Conferencing licenses, see Audio Conferencing pay-per-minute<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Faudio-conferencing-pay-per-minute&data=04%7C01%7CTony.Smith%40microsoft.com%7C959876559fa148e2ab6508d6ea9909c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954340347934641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=dF8cxAxdiKusn1fEgsYnGhwDX8sJ8dn7rN%2F1DmhvMHc%3D&reserved=0>.

  1.  Find out if Audio Conferencing is available in your country/region. Country and region availability for Audio Conferencing and Calling Plans<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fcountry-and-region-availability-for-audio-conferencing-and-calling-plans%2Fcountry-and-region-availability-for-audio-conferencing-and-calling-plans&data=04%7C01%7CTony.Smith%40microsoft.com%7C959876559fa148e2ab6508d6ea9909c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954340347944655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=dkVGQlEMDO2qTMKKsVFHkDWJE24pQRbiX7vqV5yMqBc%3D&reserved=0>.
  2.  Get your Audio Conferencing licenses. To acquire pay-per-minute licenses, please contact your account representative.
  3.  Set up Communications Credits for your organization<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fset-up-communications-credits-for-your-organization&data=04%7C01%7CTony.Smith%40microsoft.com%7C959876559fa148e2ab6508d6ea9909c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954340347944655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=H7xHoyH2suCTtT8kj5jqlO52qShBQ%2F%2B4Vz3SUBnj3FA%3D&reserved=0> for your organization by following "Step 2: Set up Communications Credits for your organization " in Set up Communications Credits for your organization<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fset-up-communications-credits-for-your-organization&data=04%7C01%7CTony.Smith%40microsoft.com%7C959876559fa148e2ab6508d6ea9909c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954340347954660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=QSW53wBUu3QhfvFd0tZmYwcelIcR8N%2BjXbpNBWQEG7M%3D&reserved=0>. To learn more about Communication Credits, see What are Communications Credits?<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Fwhat-are-communications-credits&data=04%7C01%7CTony.Smith%40microsoft.com%7C959876559fa148e2ab6508d6ea9909c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954340347964669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=W0QLti9Tpsh6Y4UnQChY9RIORb7x53fpLvI3fOl6nIY%3D&reserved=0>
Important: If Communications Credits haven't been set up, Audio Conferencing won't work for any users with pay-per-minute licenses. Also, if you have Audio Conferencing pay-per-minute licenses, you don't have to assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage (you might still need to assign them for other service

  1.  Assign or remove licenses for Office 365 for business<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.office.com%2Farticle%2F997596b5-4173-4627-b915-36abac6786dc&data=04%7C01%7CTony.Smith%40microsoft.com%7C959876559fa148e2ab6508d6ea9909c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954340347974674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=KhN5eZNzR8RZHU0cd%2F00qK0IQj6n0pZYymWobjHb2hI%3D&reserved=0> you purchased to the people in your organization who are going to schedule or lead meetings.
Thanks,
Oscar

**Comment by msbemba** [comment]
@tonysmit I have created a New PR https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/2412 with the changes requested.

**Pull request merged**
