### PR TITLE
Adjust to current menu options

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9167

### CODE REVIEW

**Comment by get-itips** [comment]
Please note : some of the build suggestions, if applied, would leave links without correct context.

**Comment by get-itips** [comment]
Fixed the suggestions that don't apply to a specific version. the remaining suggestions are for version-specific links in context and should be left like that.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@dstrome

**Comment by get-itips** [comment]
@tiburd Can you please help me with review and merge? Thanks

**Comment by get-itips** [comment]
image

image

image

**Comment by tiburd** [comment]
Thanks for the screenshots - confirmed + merging.

**Pull request merged**
