### PR TITLE
Update teams-recording-policy.md

### PR DESCRIPTION
**Pull request by SamChung-MS**
Moving ASC to a certified partner list.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Please delete ASC Technologies from Line 297 (partners in the process of certifying their solution for Microsoft Teams).

**Comment by SamChung-MS** [comment]
@JohanFreelancer9 is right, I should have deleted ASC from the bottom table. I think I made the edits to the PR. Can you please review and let me know if I need to fix it still?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cabailey PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by cabailey** [comment]
#sign-off

**Pull request merged**
