### PR TITLE
Adding 2.4.0-preview

### PR DESCRIPTION
**Pull request by get-itips**
@pupara can you kindly help me getting the change log for the 2.4.0-preview? I appreciate it.

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7516

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — COMMENTED** [review]
@scanum - I'll do the copy review once the changes have been completed. Thanks.

**Comment by get-itips** [comment]
@pupara Can you help me with this? Thank you

**Comment by get-itips** [comment]
closing as the article was updated.

**Pull request closed without merging**
