### PR TITLE
Fixing broken link

### PR DESCRIPTION
**Pull request by TokyoScarab**
fixed broken link(404) to point to similar helpful page

### CODE REVIEW

**Comment by kenwith** [comment]
Please make sure /en-us/ is not in any links as that is a language specifier. Without a language specifier in URL the page will open in whatever language the users web browser is set to use.

Let's confirm with @CarolynRowe if the link is correct too.

**Comment by jambirk** [comment]
There have been a few cases lately of links that HAVE to go to en-us or they 404, usually  links to the product catalog.

**Comment by kenwith** [comment]
@jambirk - seems to work fine for me: https://docs.microsoft.com/skypeforbusiness/skype-for-business-hybrid-solutions/plan-your-phone-system-cloud-pbx-solution/plan-phone-system-with-on-premises-pstn-connectivity    Are you getting a 404?

**Comment by jambirk** [comment]
No, that one works okay for me. I think it's just links away from docs but still within microsoft we may need to worry about.

**Pull request merged**
