### PR TITLE
Updating members

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6157

@MikePlumleyMSFT can you confirm that the naming policy of groups in Teams is now GA ? Thank you

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@mikemcleanlive can you review?

**Comment by MikePlumleyMSFT** [comment]
@ArunMSFT can you review?

**Comment by ArunMSFT** [comment]
> @ArunMSFT can you review?

@MikePlumleyMSFT - This is related to the MS Teams feature, we should loop in their PMs.

**Comment by get-itips** [comment]
@abgupta @MikePlumleyMSFT Can you kindly review and merge? Thanks

**Comment by Kateyanne** [comment]
via email Abhishek Gupta (TEAMS) <abgupta@microsoft.com> : Looks good!

**Pull request merged**
