### PR TITLE
Update what-is-phone-system-in-office-365.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2545
Changed link.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by CarolynRowe** [comment]
@scanum:  Use this link instead, then I'll approve the PR.  Thanks.

https://docs.microsoft.com/en-us/SkypeForBusiness/hybrid/msft-telephony-solutions

**Comment by scanum** [comment]
Thanks @CarolynRowe

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@scanum done thank you.

**Pull request merged**
