### PR TITLE
Updated "Available in these regions" section plan-for-teams-live-events.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4572

@LanaChin could you kindly confirm it´s related to Media Services? I think so.

### CODE REVIEW

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Thanks @dariomws for making the updates to clarify the regional data centers vs country-specific data locations.

**Pull request merged**
