### PR TITLE
Update Firewall portion or create new doc.

### PR DESCRIPTION
**Pull request by SamCosby**
Added update for script for Admins to block the Teams firewall prompt. This should either be done here or created via a new page entirely. Thanks to Rebecca Valdivia & Carolyn Blanding for the script.

### CODE REVIEW

**Comment by kenwith** [comment]
@SamCosby - thanks Sam!

@LolaJacobsen OK to merge?

**Comment by LolaJacobsen** [comment]
@voltarone & @juturu - OK to merge?

**Comment by kenwith** [comment]
@voltarone and @juturu - ping on this one...

**Comment by kenwith** [comment]
@voltarone and @juturu - ping on this one...  might be out for holidays?

**Comment by AndreaBarr** [comment]
@SamCosby Can you sign the CLA so it can pass all the checks and get reviewed for merging?

**Comment by AndreaBarr** [comment]
@SamCosby Can you sign the CLA so it can pass all the checks and get reviewed for merging?

**Comment by kenwith** [comment]
@SamCosby - would you please click the sign CLA above so the checks pass?

**Comment by kenwith** [comment]
Closing as communicated with Sam and change was already made in docs.

**Pull request closed without merging**
