### PR TITLE
Teams Meeting limit

### PR DESCRIPTION
**Pull request by dipinn26592**
Till end of CY21 irrespective of license any user can create a 1000 participant meeting. After Dec CY21 only E3/E5/A3/A5 SKU are allowed to create 1000 participant meeting and other sku limit will be 300

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by dipinn26592** [comment]
Hello @JohanFreelancer9 @scanum - what are the next steps. Is there any other action needed from my side which would help with  document update

**Comment by JohanFreelancer9** [comment]
@dipinn26592 - No further action is required from you at this time.

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by SerdarSoysal** [comment]
pls do not merge yet

**Comment by SerdarSoysal** [comment]
While we do appreciate the contributions, as the product group we believe that the addition doesn't provide any new information.

**Pull request closed without merging**
