### PR TITLE
Updated download links in teams-for-vdi.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4712

@LanaChin could you kindly double-check it?

I have updated the links with these:
https://docs.microsoft.com/microsoftteams/msi-deployment
I think in this way you always get the latest MSI.

Also, there was an issue where you updated the links:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4019
But in this way, we always need to update the links for each new version.

Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Looking into this.

**Comment by LanaChin** [comment]
Thanks @dariomws.  These changes are the same as in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5053/files. That one is merged, so closing this one.

**Pull request closed without merging**
