### PR TITLE
Update see-a-list-of-audio-conferencing-numbers-in-teams.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7152
Fixed link.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by Reeced40** [comment]
@tonysmit

**Comment by scanum** [comment]
@tonysmit Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by tiburd** [comment]
reviewed + confirmed

**Pull request merged**
