### PR TITLE
Fixing System Reqs Link

### PR DESCRIPTION
**Pull request by get-itips**
Fixing System Reqs Link according to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/990 @yogkumgit

### CODE REVIEW

**Comment by jambirk** [comment]
@MicrosoftHeidi should approve this.
all the links in the changed section still look malformed to me.

**Comment by MicrosoftHeidi** [comment]
This should not be merged, those articles aren't in the 2019 branch and so are incorrect.

**Comment by SerdarSoysal** [comment]
@jambirk there seems to be a TOC issue with this topic in the 2019 TOC. When you click on the "create a file share" link in the 2019 TOC, you fall back into the 2015 TOC, and in that context the links in the article are correct as @MicrosoftHeidi says. Can you please investigate what needs to be done to fix the 2019 TOC?

**Comment by jambirk** [comment]
Agree with Heidi this should not be merged. This is an evergreening issue/misunderstanding: the article in question is used by both versions, and depending on which version of SfB the reader needss to install they need to go to different requirements topics, which are not shared. having a look at the TOC next.

**Comment by get-itips** [comment]
Thanks @jambirk for clarification.

**Pull request closed without merging**
