### PR TITLE
Update important note steps in Exchange-Teams-interact.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7419.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dstrome Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by tiburd** [comment]
@get-itips @tseward 

Hello,

This is an old PR. Dario says it's still relevant but suggested having you two check to confirm - please approve if you agree. 

After you both review it, please @ mention me.

Thank you!

**Review by tseward — APPROVED** [review]

**Comment by tseward** [comment]
@tiburd provided this is still an applicable fix, I'm good with it.

**Review by get-itips — APPROVED** [review]

**Pull request merged**
