### PR TITLE
Update CQD-teams-aa-cq-historical-report.md

### PR DESCRIPTION
**Pull request by CLYVR**
Typo correction.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@msmikedavis PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CLYVR** [comment]
Conflicts resolved

**Comment by CLYVR** [comment]
Have redirected AA/CQ report entry on main CQD page to a centralized page in AA/CQ documentation - this PR no longer required.

**Pull request closed without merging**
