### PR TITLE
Update stream-classification-in-call-quality-dashboard.md

### PR DESCRIPTION
**Pull request by sjaligam-MS**
For Satin code changes, Audio classifier needs to omit "Audio Degradation Avg"  and "Ratio Concealed Samples Avg" while determining PCR.

### CODE REVIEW

**Comment by sjaligam-MS** [comment]
For Satin code changes, Audio classifier needs to omit "Audio Degradation Avg" and "Ratio Concealed Samples Avg" while determining PCR.

**Review by sjaligam-MS — COMMENTED** [review]
@Priteshkanani @GageAmes : Please Review

**Comment by GageAmes** [comment]
@sjaligam-MS Doesn't the classifier only change when the SATIN codec is in use? For codecs other than SATIN, is the old classifier supposed to be retained?

**Review by GageAmes — CHANGES_REQUESTED** [review]
The previous classifier logic is still used for non-SATIN codecs, correct?

**Pull request closed without merging**
