### PR TITLE
Update limits-specifications-teams.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5103
Added note.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@nej-nej please review this PR and let us know whether it's OK to merge.

**Comment by nej-nej** [comment]
Adding @Gaurav<mailto:Gaurav.Pancholi@microsoft.com>/ @Namendra<mailto:Namendra.Kumar@microsoft.com>, can you please let us know if this is correct ?

This is a PR to update the user facing docs: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5269/files

**Comment by nej-nej** [comment]
@Neeraj<mailto:nej@microsoft.com> - The meeting expiration section in this doc correctly describes the expiration time: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

From: Neeraj Jain <nej@microsoft.com>
Sent: Friday, July 10, 2020 5:22 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>; Gaurav Pancholi <Gaurav.Pancholi@microsoft.com>; Namendra Kumar <Namendra.Kumar@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update limits-specifications-teams.md (#5269)

Adding @Gaurav<mailto:Gaurav.Pancholi@microsoft.com>/ @Namendra<mailto:Namendra.Kumar@microsoft.com>, can you please let us know if this is correct ?

This is a PR to update the user facing docs: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/5269/files<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fpull%2F5269%2Ffiles&data=04%7C01%7CGaurav.Pancholi%40microsoft.com%7C6fcab24af24b41f6040008d824cbea4f%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637299805575167342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gD5qaL%2FsS4NRxnQ5c39yPH7fRnmsde2IvqH8CjDKRew%3D&reserved=0>

**Comment by LolaJacobsen** [comment]
Merging per @nej-nej @Gaurav0327

**Pull request merged**
