### PR TITLE
Update clients-and-devices.md

### PR DESCRIPTION
**Pull request by robertpp**
Minor change to eliminate the confusion generated by the use of the old denomination in the article title.

### CODE REVIEW

**Comment by kenwith** [comment]
@jambirk - looks like there is a conflict.. can you check?  @robertpp - thanks for your contribution and making the docs better!

**Comment by jambirk** [comment]
Guidance from Phillip Garding, reviewer for the topic, is not to approve this. Closing the PR.

**Comment by kenwith** [comment]
I am not exactly sure why this PR was closed. It looks like the edit that @robertpp made is accurate. It is just retitling an article the link goes to. When I go to the article the link @robertpp looks correct to me. Am I missing something @jambirk ?

**Comment by kenwith** [comment]
It looks like since @robertpp made his update though the article name has been changed again and that is what is causing the conflict. I am going to fix that and then merge this PR unless anyone sees something I am missing. @robertpp - much appreciated you taking the time to make the docs better.

**Pull request merged**
