### PR TITLE
update restrictions

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8592

source https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=music%2Con%2Chold

### CODE REVIEW

**Comment by scanum** [comment]
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
Let's make sure @JensTrier approves of this change before we merge.

**Comment by JensTrier** [comment]
@CarolynRowe thanks for tagging me. Please hold until I get this confirmed

**Comment by JensTrier** [comment]
@CarolynRowe got confirmation that GCC is fine. Please merge

**Pull request merged**
