### PR TITLE
Adding Maximum Limit to Message section

### PR DESCRIPTION
**Pull request by SamCosby**
Teams Group Chat only allows 20 people to have AV at any point..

Found here: https://domoreexp.visualstudio.com/Teamspace/_git/Teamspace-Web?path=%2FWebClient%2Fsrc%2Fapp%2Fcomponents%2Fchat-header%2Fchat-header.spec.ts&version=GBdevelop

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@karvell - please review.

**Comment by scanum** [comment]
@karvell Any updates? Thanks!

**Comment by LolaJacobsen** [comment]
I'm handling this separately and will make the needed updates there.

**Pull request closed without merging**
