### PR TITLE
Update meeting-policies-participants-and-guests.md

### PR DESCRIPTION
**Pull request by lindspea**
Fixes # https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9591 
Fixed link

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@mkbond007
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@mkbond007
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
Closing out old PRs.

**Pull request closed without merging**
