### PR TITLE
Collaborations bars rename (device-management.md)

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8277.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
@cazawideh - can you confirm these changes are ok?

**Comment by cazawideh** [comment]
@scanum Collaboration bars should be changed to as 'Teams Rooms on Android,' to prevent any confusion with Teams Rooms on Windows

**Comment by dariomws** [comment]
@cazawideh, do you think we should change "Collaboration bars" to "Teams Rooms on Android" here? I think it's talking about both types of rooms, not only Android.

**Comment by cazawideh** [comment]
@dariomws If it applies to both, then "Teams Rooms" is fine. If the information only applies to collaboration bars, please use "Teams Rooms on Android"

**Comment by dariomws** [comment]
@cazawideh, yes, this article does not distinguish between "MTR on Windows" or "on Android". It applies to both, so I have changed "Collaboration bars" to "Teams Rooms" or "Microsoft Teams Rooms".

Thanks!

**Review by ganselme — APPROVED** [review]

**Pull request merged**
