### PR TITLE
Fixed typo (calcuate)

### PR DESCRIPTION
**Pull request by hubalazs**

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@NMuravlyannikov

**Comment by NMuravlyannikov** [comment]
Sounds good.

**Comment by NMuravlyannikov** [comment]
@scanum  do I have rights to merge? I don't see any button.

**Comment by scanum** [comment]
@CarolynRowe Hi Carolyn, could you please help us merge this request. I don't think Nikolay has rights. Thanks!

**Pull request merged**
