### PR TITLE
Issue #3168 Correction on link

### PR DESCRIPTION
**Pull request by j0rt3g4**
I've corrected the link as mentioned on issue #3168

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@j0rt3g4 Can you please change author to Ken? Thanks!

**Comment by j0rt3g4** [comment]
@scanum  Done

**Comment by j0rt3g4** [comment]
@kenwith are you are to review and merge this content? (thank you!)

**Comment by j0rt3g4** [comment]
Updated with #3420

**Pull request closed without merging**
