### PR TITLE
Update server-requirements.md

### PR DESCRIPTION
**Pull request by dariomws306**
Added .net 4.7.2 support.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@jambirk @CarolynRowe @MicrosoftHeidi Can I merge this?

**Comment by kenwith** [comment]
Looks good, I have a long thread on this one so went ahead and merged it. :) Terry Adams provided the approval.

**Comment by VladimirGluten47** [comment]
Apologies if I am mistaken but this seems to have regressed back to showing .NET 4.7.1 as the highest supported version: [Source](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/server-requirements#Software).

**Comment by dariomws306** [comment]
@kenwith could you help with this new PR? We have confirmed internally 1 year ago that 4.7.2 is supported on CU6 or later.

**Pull request merged**
