### PR TITLE
Updated Cloud Auto Attendant migration deadline

### PR DESCRIPTION
**Pull request by ndambrosio**
Customers must migrate their auto attendants by February 28, 2020.   We need to update the auto attendant migration in the article from February 1, 2020 to February 28, 2020

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by ndambrosio** [comment]
Any update on this merge?  This is generating a bunch of support cases as it's misleading customers.  Thank you.

**Comment by SerdarSoysal** [comment]
@waseemhashem we're ready to merge this. Pls confirm the date from the PG side before we do so.

**Comment by waseemhashem** [comment]
Confirmed, please proceed.
Thanks

**Pull request merged**
