### PR TITLE
[DO NOT MERGE] SEO edits cloud-voice-landing-page

### PR DESCRIPTION
**Pull request by jdmartinez36**
Edited description for length and keywords, added Microsoft Teams VoIP to intro per recommendation. Did not remove Microsoft Teams from title per recommendation; Google search showed that this doc does not have the product suffix.

For review by @DaniHalfin

### CODE REVIEW

**Comment by DaniHalfin** [comment]
I'm reviewing. Thanks.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@DaniHalfin Hi! Is this PR going to be closed? Thanks!

**Comment by jdmartinez36** [comment]
Hi @DaniHalfin 

It looks like Lola had approved this PR with changes she made herself.

**Pull request merged**
