### PR TITLE
chore: Add passing Markdownlint config

### PR DESCRIPTION
**Pull request by nschonni**
Suppressed all currntly failing rules.
Makes it less noisy editing with the MS Docs Authoring Pack

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@dstrome could you look at this one?

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
I'm not going to approve this change at this time. However, we'll review the markdownlint config syntax and, if it makes sense, will apply this broadly across the repos. Thanks for suggesting this @nschonni.

**Comment by nschonni** [comment]
No problem, but note that it is already in azure-docs, dotnet, visualstudio, aspnet, etc...
Although only some teams actually laid out a preference of the rules vs. just adding the config like this and then cleaning up

**Comment by dstrome** [comment]
Yup, understood. This is more a matter of ensuring that our repo configs are consistent. We have a few dozen repos and I want to avoid one-off configurations. This is something that makes sense to apply broadly so we'll investigate and roll out across our repos in a controlled way.

**Pull request closed without merging**
