### PR TITLE
Update recommended setting for Conference Mode in create-a-phone-system-call-queue.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7625.

### CODE REVIEW

**Comment by dariomws** [comment]
@CLYVR I see that you added this note 23 days ago. I'll appreciate it if you confirm that **On** is the new recommended value. Thanks!

**Comment by CLYVR** [comment]
@dariomws Confirmed, On is the recommended value for Conference mode.

**Comment by dariomws** [comment]
Thank you so much as always for your help @CLYVR!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by CLYVR** [comment]
@dariomws @JohanFreelancer9 - I tried to modify this PR but couldn't - please note that there is one other location where "Auto" needs to be changed to "On"

Near the bottom of the page there is:

> Summary of recommended call queue settings
> The following settings are recommended:
> 
> Conference mode to **Auto**

Thanks!

**Review by JohanFreelancer9 — APPROVED** [review]
@CLYVR - unfortunately I cannot edit outside the scope of the PR to implement your further change. It should be possible for you to edit this PR, failing which, you might need to open an additional PR to address that change. Many thanks.

**Comment by dariomws** [comment]
@CLYVR @JohanFreelancer9 done!

**Comment by JohanFreelancer9** [comment]
Thanks, @dariomws!

**Comment by scanum** [comment]
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
