### PR TITLE
 Proposing to clarify every log location on windows

### PR DESCRIPTION
**Pull request by get-itips**
Fixes carrier returns
Fixes asterisk escape character
Proposes clarifying log file location when using Windows

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7788

### CODE REVIEW

**Comment by francisco-lafe** [comment]
I like it!

**Comment by francisco-lafe** [comment]
I like it!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
