### PR TITLE
Updated the Theming template to the latest photoshop cc version

### PR DESCRIPTION
**Pull request by j0rt3g4**
Added new version for the latest photoshop cc. #2906

### CODE REVIEW

**Comment by LolaJacobsen** [comment]
@jambirk - for your review.

**Comment by jambirk** [comment]
The file is linked by way of an fwlink. The fwlink needs to be updated. There's no reason to change the link in the article itself. I'll sort this out later today.

**Comment by j0rt3g4** [comment]
@jambirk  Yes, I thought the best way is to get them all on the repository, but you can save the new file on the result of the fwlink either way.

Thank you

**Comment by jambirk** [comment]
Template file has some branding issues anyway, uploading that version is premature.

**Comment by j0rt3g4** [comment]
@jambirk Alright, so how do we work around this to solve the issue?

**Comment by jambirk** [comment]
@j0rt3g4 and @scanum  This template update was still being discussed and hadn't been approved by the PMs yet. The PR was premature. I will continue dialog and handle further Issue resolution and PR changes.

**Pull request closed without merging**
