### PR TITLE
Fix 'Stream classic migration' link

### PR DESCRIPTION
**Pull request by lryanuk**
Existing link invalid, updated to go to Stream Classic Migration Overview page

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by JohanFreelancer9** [comment]
@lryanuk, I notice that you have closed its PR. Was that intentional?

**Comment by lryanuk** [comment]
> @lryanuk, I notice that you have closed its PR. Was that intentional?

Yes, this PR is no longer valid as the text has been updated since I fixed the link

**Pull request closed without merging**
