### PR TITLE
Reflecting the new UX/UI in TAC

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7900

given the re-organization of the menu and menu options in the TAC, tried to reflect those changes in this article.

@SerdarSoysal please let me know if you agree with these changes, thanks

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@SerdarSoysal Can you help me getting this merged? Thank you

**Comment by get-itips** [comment]
@tiburd Tina, can you help me getting this merged please?

**Pull request merged**
