### PR TITLE
Added more information about Exchange Hybrid checkbox to Exchange-Teams-interact.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6949.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
@scanum @JohanFreelancer9 @Kateyanne Please make sure to look for absolute links to pages on docs.microsoft.com and change them to relative. Boils down to, if you see a link with https://docs.microsoft.com in it, remove the https://docs.microsoft.com portion, leaving the remaining portion of the url in place.

For example, this link is an absolute link:
```
https://docs.microsoft.com/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback
```
The following is that link but changed to be relative:
```
/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback
```
Do this only with docs.microsoft.com links. Links to other location, including other microsoft.com sites like support.microsoft.com, still need to be absolute links.

**Comment by dariomws** [comment]
Thank you @dstrome!

We've been informed about this on April 26. Older PRs have absolute links.

**Pull request merged**
