### PR TITLE
Added note about Compliance Recording with an SBA to teams-recording-policy.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8383.

@cabailey, could you kindly review it? Thanks!

### CODE REVIEW

**Comment by cabailey** [comment]
I don't have the technical knowledge to approve this change and need to assign to @SamChung-MS

**Comment by SamChung-MS** [comment]
Actually I'm no longer on Compliance Recording. Can you please assign this to @2kiran? He owns this area now.

**Comment by cabailey** [comment]
@SamChung-MS   Please send me his Microsoft alias - privately if you prefer.

**Comment by SamChung-MS** [comment]
Message sent in Teams.

**Review by 2kiran — APPROVED** [review]

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by cabailey** [comment]
Looks like PM-approved & copy-editing approved.  Merging.

**Pull request merged**
