### PR TITLE
Classic Logs

### PR DESCRIPTION
**Pull request by CarolynBillups**
Classic Logs are no longer available. Update screen shots and change from **Logs (Classic)** to Logs.

### CODE REVIEW

**Comment by scanum** [comment]
@jambirk Changes look correct, can this be merged? Thanks

**Comment by jambirk** [comment]
The comment about the screen shots requires further action. @LanaChin is currently working on updates to this page in another branch. Lana, can you make this change in the rebrand update, and catch the screen shot while you're there? Then we can close this PR while resolving the core issue in that other branch.

**Comment by jambirk** [comment]
@LanaChin  please respond, if you're already able to address this in the rebrand branch we should close this.

**Comment by LanaChin** [comment]
Yes, I'll address these changes as part of the rebrand update. Closing this PR.

**Pull request closed without merging**
