### PR TITLE
Updated license requirements in rooms-licensing.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5920.

@flinchbot could you kindly confirm this information? I see that you added the requirements for this option without DR. Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Microsoft Teams Rooms article - assigning to dstrome.

**Comment by dstrome** [comment]
The article is correct. If you don't have Direct Routing, you must have one of the following for the meeting room to receive or make calls from or to an external number:

Domestic or International Calling Plan
Microsoft 365 Business Voice

**Comment by dariomws** [comment]
@dstrome Don't need a meeting room SKU too?

**Comment by dstrome** [comment]
The row in question is specific to calling ability. Other functions of the device require the Meeting Rooms SKU.

**Comment by dariomws** [comment]
Thanks @dstrome!

**Pull request closed without merging**
