### PR TITLE
Update direct-routing-plan.md

### PR DESCRIPTION
**Pull request by gerriejoubert**
+SIP/TLS|SBC|SIP Proxy|Defined on the customer Firewall|5061 (Ensure that TCP 5061 is open on the firewall for inbound and outbound traffic)|

### CODE REVIEW

**Comment by gerriejoubert** [comment]
+SIP/TLS|SBC|SIP Proxy|Defined on the customer Firewall|5061 (Ensure that TCP 5061 is open on the firewall for inbound and outbound traffic)|

Customers are notifying us that there are no clear information on the port configuration within their firewall.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by gerriejoubert** [comment]
Thank you

**Comment by JohanFreelancer9** [comment]
Hi @gerriejoubert, Could you please reopen this PR so that it can be approved by the doc owner/manager and merged. Please only close your original PR #7677. Thanks.

**Pull request closed without merging**
