### PR TITLE
Update Known-issues.md

### PR DESCRIPTION
**Pull request by laujan**

### CODE REVIEW

**Comment by LolaJacobsen** [comment]
@marclauinger - please review

**Comment by marclauinger** [comment]
@laujan , Are there specific apps that are affected?  If only happening with Chrome version 80, why aren't we working with chrome to fix issues?  Seems a little to broad for this article.

**Comment by laujan** [comment]
Hi @marclauinger<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarclauinger&data=02%7C01%7Cjanuari.la%40microsoft.com%7C614670c7dc33431e91ae08d7a4e5f17d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637159179816428396&sdata=RI%2F%2BGDIe8q7S8XZfVqcwtSmDx%2Ber%2BfB%2FMKCJv3iDCxY%3D&reserved=0>,

I checked with the PM working on the issue:

Are there specific apps that are affected?

Yes, however, we can't account for all of our line-of-business applications — we have limited visibility. Therefore, we can't provide a comprehensive list of apps - we just know some apps are affected. Our first-party (and most of our third-party) applications are already fixed.

Why aren't we working directly with Chrome?

This change is being forced by the Chrome team and will affect hundreds of thousands of sites across the internet on Feb 4th, when this security/privacy change becomes public. It's up to our app developers to make the changes (we can only push/encourage these developers to make the changes; and we've being doing that quite extensively). Unfortunately, not every app developer has the time/motivation to make these changes in time. There's nothing we (Teams Platform) can do to mitigate this issue — our app developers must make the change. However, we do want to provide information for our app developers when or if they encounter the redirect issue.
Read more here: https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

Thanks!

La

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.
--

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@marclauinger where are we at with this one?

**Pull request merged**
