### PR TITLE
screenshot of Org-wide settings is out of date

### PR DESCRIPTION
**Pull request by VLG17**
i have added the correct screenshot to the issue thread (i don't have right to upload the file to the /media directory)

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2848

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@LanaChin  Hi! Following up on this issue, please let me know if there is anything I can do to help!.

**Comment by LanaChin** [comment]
@scanum - the image was removed but not replaced with a new image.

**Comment by LanaChin** [comment]
@vlg17, can you submit the image in the PR?  thanks.

**Comment by VLG17** [comment]
> @VLG17, can you submit the image in the PR? thanks.

@LanaChin The correct image is in the PR Thread. I don't have the right needed to upload the image to the repository, if that's what you mean.

**Comment by LanaChin** [comment]
@kenwith - can you help me out with how the image from @VLG17 can be added to the PR?  Thanks!

**Comment by kenwith** [comment]
@VLG17 - what you can do for an image is submit it as a PR. You add it to the correct location in your fork of the main repo and then commit that file and include it in the PR. Let me know if you get stuck or have questions.

**Comment by VLG17** [comment]
@kenwith thank you for the info. I hope i did the right thing now.

**Comment by LanaChin** [comment]
@VLG17 - I don't see the image in the MD file yet. Can you add markdown in the MD file to include the image?  Thanks.

**Comment by VLG17** [comment]
@LanaChin is it ok now? The image is in my repository. I don't have rights to add it to the main repro. Hope this is enough.

**Comment by kenwith** [comment]
@VLG17 you should submit the image as part of the PR. Nobody has rights to add to the repo directly so it should come in as a PR. If you get stuck let me know and I can help.

**Comment by VLG17** [comment]
> @VLG17 you should submit the image as part of the PR. Nobody has rights to add to the repo directly so it should come in as a PR. If you get stuck let me know and I can help.

@kenwith I did just that, or at least i think i did...

image

**Comment by kenwith** [comment]
@VLG17 Sorry, maybe I am missing another PR. I looked at the Files Changed tab and didn't see the image in this PR but maybe it is in another PR? If the image you are linking is already in the /image folder then this PR should be good to go. If not then it would show a broken image. 

What are your thoughts? Should I go ahead and merge it?

**Comment by LanaChin** [comment]
@VLG17 - per @kenwith, the image needs to be included in the PR. In the last commit, you added markdown to the MD file to reference the image but the image PNG file also needs to be included. Thanks!  @kenwith - correct me if I'm mistaken.

**Comment by VLG17** [comment]
@LanaChin The file is under /images in my repository (fork of the project) and i've referenced it. I don't know how to add the PNG file to the PR.

Could you please help with a guide or some steps? I thing i'm missing an easy step. I'll keep looking.

**Comment by kenwith** [comment]
@VLG17 - yes, I can help.. ping me on chat. In a nutshell, you add a file to your repo: https://help.github.com/en/articles/creating-new-files then you create a PR from your fork for whatever branch you added it to: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by LanaChin** [comment]
@VLG17 - can you please rename the PNG file?  Your file name is65018777-8be2ce80-d932-11e9-8351-fff4d55fa070.png. Please rename it so that it's the same as the original file name, which is
app-permission-policies-org-wide-settings.png.  Also, remember to update the markdown in the MD file too. Thanks.

image

**Pull request merged**
