### PR TITLE
Added metadata description value

### PR DESCRIPTION
**Pull request by jdmartinez36**

### CODE REVIEW

**Comment by 1justingilmore** [comment]
@traya1

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by jdmartinez36** [comment]
@Dani.Halfin@microsoft.com

P2 meta description additions for merge/review via Aquent.

**Comment by scanum** [comment]
@rowille PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by jdmartinez36** [comment]
@DaniHalfin

**Pull request merged**
