### PR TITLE
Clarifying on-premises Exchange requirements

### PR DESCRIPTION
**Pull request by felgar73**
Changes proposed per my feedback in the article discussing the need for hybrid configuration in Exchange.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
@felgar73 thanks for the update. I've incorporated your changes. Please make sure to delete and recreate your fork, or use git bash to update it from the upstream repo live branch. There were some changes in there that conflicted with yours.

**Comment by felgar73** [comment]
Thanks David. I’m new to the process, so just want to be clear; am I deleting as shown below?

[cid:image001.jpg@01D60D1A.347CC030]

-Felix G.

**Pull request merged**
