### PR TITLE
Update Poly Studio X30/50/70 and G7500 supported firmware

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9950

https://www.poly.com/ch/fr/support/knowledge-base/kb-article-page?type=Support+Information&lang=en_US&urlName=PolyOS-4-0-0-removed-from-MS-TAC&t=all&k=Poly%C2%A0Studio%C2%A0X70

### CODE REVIEW

**Comment by dariomws** [comment]
@davebirr @dstrome, please review.

Do we also need to update X70 to 3.12.0.366027 in the table?

Do we also need to update the following article?
https://learn.microsoft.com/microsoftteams/rooms/android-app-firmware

Once PolyOS 4.0 is available in the TAC, we'll have to update the articles again.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
Getting confirmation of change.

**Comment by dstrome** [comment]
The article is correct. We're submitting a request to Poly to update or remove their post. Closing this PR.

**Pull request closed without merging**
