### PR TITLE
Update data-collection-practices.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3868

I couldn't find a article to replace it, so I had to remove it.

### CODE REVIEW

**Comment by ScapyArtGroup** [comment]
Update data-collection-practices.md #4065

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tonysmit** [comment]
@dariomws - appreciate the feedback and corrections you have submitted! Do you work for MS?

**Comment by dariomws** [comment]
@tonysmit I'm not a Microsoft employee but I'm a freelancer contracted to help to improve docs.

**Pull request merged**
