### PR TITLE
re-entered the portal.azure.com URL

### PR DESCRIPTION
**Pull request by Jcoetsee**
this refers to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2028

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@somakbhattacharyya Changes look correct. Could you please review and merge? Thanks!

**Comment by Jcoetsee** [comment]
Just following up on the above @somakbhattacharyya if you can please review and merge?

**Comment by scanum** [comment]
@SerdarSoysal @somakbhattacharyya Any updates on this? Thanks!

**Pull request merged**
