### PR TITLE
Updating CQD access permisions

### PR DESCRIPTION
**Pull request by MattWade-MS**
Needed to update CQD access permissions for new Team's based roles.  Also made some minor edits for consistency with other public documentation.

### CODE REVIEW

**Comment by kenwith** [comment]
@jambirk - I am not familiar with this article and the   "ms.author" just says MS Advisor? Any idea who owns this or what to do with this one?  FYI @scanum

**Comment by jambirk** [comment]
@rmw2890 is the author

**Comment by kenwith** [comment]
@rmw2890 I added a commit to update the 'ms.author'.   @scanum FYI

**Comment by MattWade-MS** [comment]
Just as an FYI, I am the official author of this article both the public and downloadable Word doc.  ;)

**Pull request merged**
