### PR TITLE
Update cortana-in-teams.md

### PR DESCRIPTION
**Pull request by arachmanGitHub**
Updating details for Cortana enablement for MTR

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
Hi @dstrome Hope you are well. Wondering if you can help with this PR? thanks

**Comment by scanum** [comment]
Hi @dstrome Wondering if you can help with this PR? Thanks.

**Pull request closed without merging**
