### PR TITLE
"Teams Communications Admin" cannot see "Analytics & reports" section under Teams admin center

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4208

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Reached out to PM.

**Comment by LanaChin** [comment]
thanks @dariomws. there were some additional updates related to this issue, so I did them in a separate branch. the docs are updated now: https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/teams-reporting-reference and https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles. closing this without merging.

**Pull request closed without merging**
