### PR TITLE
Update availability-in-the-united-states-u-s.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9165.

### CODE REVIEW

**Comment by dariomws** [comment]
@Benny-54 @CarolynRowe, could you kindly double-check this? Due to tax issues, I understand that the pay-as-you-go calling plan is unavailable in the US and PR.

Thanks!

**Comment by CarolynRowe** [comment]
Looping in @DaniEASmith who is working on this...

**Comment by DaniEASmith** [comment]
@dariomws I'm working on publishing a PR: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/pull/10104.

The PR I linked includes information for the 2 zones of PAYGo licenses. According to the PM, Chandra Kilaru, Zone 1 is specifically for the U.S. (including Puerto Rico) and Canada.

**Comment by DaniEASmith** [comment]
@dariomws I've confirmed with the PM that Pay-as-you-go Calling Plans is NOT available in the US and Puerto Rico. It is available in Canada. This PR is thus valid.

**Pull request merged**
