### PR TITLE
Update information-barriers-in-teams.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2144
Changed required licenses and permissions wording.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
I've asked PM Vikram Jungali to review.

**Comment by lindspea** [comment]
Hi there. Thanks @Lola Jacobsen <lolaj@microsoft.com> and @denisebmsft.
There is a merge conflict in 2178.  The sentence should read "Currently,
the information barrier features are in public preview. When these features
are generally available, they'll be included in the following
subscriptions:"
The reason this happened I think is because there was an issue I created a
PR for and then there was another issue after that where the wording was
changed again and not sure which one was merged first...

[image: Picture]

**Comment by lindspea** [comment]
Lindsay, I see that you CLOSED the PR, but it doesn’t look like it got merged (Denise approved it but didn’t merge it AFAICT). It doesn’t look like it got merged. (Maybe I’m reading it wrong…)



Lola Jacobsen | Team MARVEL (formerly MAX)
Senior Technical Writer
Microsoft Teams
Microsoft 365
[cid:image002.png@01D38602.D9260340]

**Pull request closed without merging**
