### PR TITLE
Update meeting-policies-in-teams.md

### PR DESCRIPTION
**Pull request by Exnav29**
Placed the "Allow Meet now in Private Meeting", "Enable Live Captions", and "Allow Chat in Meetings" into the "Meeting Policy Settings - Participants and Guests" section of the document since this is where the settings are located in the Teams Admin Center.  I also deleted the "Coming Soon" text on them as they have been released to GA.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmitPR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@tonysmit Hi Tony! Hope you are doing well. PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by rjagiewich** [comment]
@tonysmit - Thanks for the confirmation to merge this one, Tony.

**Comment by tonysmit** [comment]
@LanaChin - Can you create a work item to update this topic? We need to revisit this article and update screenshots and the settings in the UX.

**Pull request merged**
