### PR TITLE
Update add-or-remove-an-emergency-address-for-your-organization.md

### PR DESCRIPTION
**Pull request by savusca**
Added additional information regarding Emergency addreses mathcing the phone number's area code.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@LolaJacobsen @tonysmit Can I merge this?

**Comment by kenwith** [comment]
@savusca - thanks for content updates, appreciated!

@msmikedavis - looks like you are listed as ms.reviewer for this article, is it OK for me to merge? You can see the change on the "Files Changed" tab and the red is removed and green is added.

**Comment by kenwith** [comment]
@tonysmit -- would you be able to confirm this or know how we can get @msmikedavis to take a look? It has been open 29 days.

**Comment by msmikedavis** [comment]
What was added for this doc isn’t accurate in many of the countries we operate.  I can’t tell in github who added it.

**Comment by kenwith** [comment]
@msmikedavis - this is a Pull Request submitted by @savusca … maybe community member or customer? 

@savusca can you fill us in a bit more on this Pull Request? Mike is the PM in charge of this product and @tonysmit is the person that owns this article.

**Comment by msmikedavis** [comment]
@ Tony Smith

Per IM today.  The statement added by Sabin is true in the Belgium, France, Germany, Ireland, Netherlands & Spain – but not in Canada, UK & US.

**Comment by kenwith** [comment]
@msmikedavis and @tonysmit - I updated the PR of @savusca to include this information. You can find link to the changes at: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/1317/files 

Looks OK to merge?

Thanks for this highly collaborative team effort to make this happen!

**Comment by msmikedavis** [comment]
Approved via github

**Pull request merged**
