### PR TITLE
Update create-a-phone-system-call-queue.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8401
Added links

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
the added links are not correct.  we should not be linking to a skype preview article.  also, i can't tell what the original request was.  what problem are we trying to fix here?  i'm going to close for now...  because i can't find the do not merge label and we should not merge the PR with the existing links.

**Comment by javiernegro** [comment]
The problem is that the documentation is unclear about the behaviour of the product.
_The documentation doesn't specify how Serial Routing works when the Agent is a teams channel.
Is there a way to set the order of the member of the group?
What criteria does it use to ring users?_

**Pull request closed without merging**
