### PR TITLE
Update location-of-data-in-teams.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3873

### CODE REVIEW

**Comment by GiantCrocodile** [comment]
I think you mean `your tenant`, not `your data`, right @dariomws?

**Comment by dariomws** [comment]
@GiantCrocodile, no I mean "your data". The picture is just an example about in which region will be located your Teams data.

**Comment by GiantCrocodile** [comment]
Ah nevermind, I did confuse myself. Your fix is good!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by GiantCrocodile** [comment]
How comes this wasn't merged @dariomws?

**Pull request closed without merging**
