### PR TITLE
Updated soft deleted period in plan-teams-lifecycle.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7179.

@MikePlumleyMSFT could you kindly help to confirm this information? I think she is right. 21 days is ok for Channels?

Thank you!

### CODE REVIEW

**Comment by MikePlumleyMSFT** [comment]
@ArunMSFT can you confirm that Teams is included in the Groups 30-day soft-delete policy?

**Comment by ArunMSFT** [comment]
You can find more information about Teams lifecycle here: https://docs.microsoft.com/en-us/microsoftteams/plan-teams-lifecycle#:~:text=Teams%20are%20actually%20deleted%20with%20a%20%22soft%20delete%22,reversed%20for%20up%20to%2021%20days%20after%20deletion.

I don't think it is same as 30days but slightly different.

**Comment by dariomws** [comment]
@ArunMSFT yes, that's the sentence we are updating if this pull request is approved.

More articles are saying 30 days:
https://docs.microsoft.com/microsoft-365/admin/create-groups/restore-deleted-group
https://docs.microsoft.com/microsoftteams/archive-or-delete-a-team

Thank you!

**Comment by ArunMSFT** [comment]
I don't know that for sure. I vaguely remember it was something less than 30. @Mike ***@***.***> - do we have any experts on Teams on the doc side.

**Comment by dariomws** [comment]
@MikePlumleyMSFT do you have any updates here? Thanks a lot!

**Pull request merged**
