### PR TITLE
Added Ribbon analog devices and small syntax change

### PR DESCRIPTION
**Pull request by FilippSe**
Added Ribbon analog devices to the table and small syntax change (EdgeMarc)

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
@FilippSe.  This branch has conflicts.  Can you resolve the conflicts?  Or resubmit?

**Comment by FilippSe** [comment]
I see. Will resubmit tomorrow and email you.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by CarolynRowe** [comment]
This was handled in another PR.  Closing this one.

**Pull request closed without merging**
