### PR TITLE
Update dynamic-memberships.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6300
Added link.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by SerdarSoysal** [comment]
@MicrosoftHeidi @MikePlumleyMSFT can you two pls review this change and advise? Not sure if directly pointing to a PS script this way is appropriate. Seems like it needs more context.

**Comment by MikePlumleyMSFT** [comment]
@SerdarSoysal agree on needing more context. But also, the script seems designed to sync membership from from the AAD group object to the Team. I don't think this would work on a team/group with dynamic membership, which is the focus of the article.

**Comment by MikePlumleyMSFT** [comment]
The added link is not related to this article.

**Pull request closed without merging**
