### PR TITLE
Update managed-meeting-rooms-portal.md

### PR DESCRIPTION
**Pull request by YuriySamorodov**
The name of the portal has been truncated on the line 66

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@altsou 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by altsou — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
Thank you @altsou I have copied David Strome for review and merging.

**Comment by scanum** [comment]
@dstrome
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request closed without merging**
