### PR TITLE
Dariomws242020

### PR DESCRIPTION
**Pull request by dariomws306**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3755

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Thanks for making the updates @dariomws306. Can you convert the .jpg to .png and then send it back to me to merge? Thanks!

**Comment by dariomws306** [comment]
@LanaChin Image was originally in png format, I think if I convert it to png we will have the same issue again.

**Comment by LanaChin** [comment]
@dariomws306 - I think that images need to be in PNG format. Will using **&#x2713;** work better? Thanks.

**Comment by dariomws306** [comment]
Thank @LanaChin! Seems that it works! Good one!

**Pull request merged**
