### PR TITLE
Update plan-teams-lifecycle.md

### PR DESCRIPTION
**Pull request by JeffBrownTech**
Added sentence in Stage 3: End, paragraph 2 to indicate that channels are also soft deleted for 21 days and can be restored before that duration.

### CODE REVIEW

**Comment by LolaJacobsen** [comment]
Confirming this change with PM Praveen Vijayaraghavan.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen Wanted to let you know PR has been copyedited and is ready for final review, just waiting on Praveen's confirmation. Does he have a GitHub user? I could not find him. Thanks!

**Comment by LolaJacobsen** [comment]
New PM contact for this feature area: Anwar Ali. I'm pinging him in Teams.

**Comment by LolaJacobsen** [comment]
@anwara-ms please review this PR and let us know whether it's OK to merge. Or give us corrections.

**Pull request merged**
