### PR TITLE
Update teams-for-vdi.md

### PR DESCRIPTION
**Pull request by laujan**

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.
--

**Comment by LolaJacobsen** [comment]
@voltarone - please review. Both sets of URLs work.

**Comment by laujan** [comment]
Hi. 
The current link,**statics.teams.microsoft.com**, will not be supported in the near future. It needs to be updated to the new link, **statics.teams.cdn.office.net**, before the old link no longer works and returns 404 errors. If you need more information on the upcoming change, please ping [Andrew Clear](clearab).
Thx!

**Comment by LolaJacobsen** [comment]
@LanaChin is working with the PM on VDI, currently publishing an overhaul of that documentation.

**Pull request merged**
