### PR TITLE
non-VDI client auto-update

### PR DESCRIPTION
**Pull request by naminakao**
According to https://docs.microsoft.com/en-us/microsoftteams/msi-deployment, non-VDI client seems auto update when it detects a new version is available.

### CODE REVIEW

**Comment by LolaJacobsen** [comment]
@voltarone - please review.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@voltarone @LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
In a 1:1 chat with @voltarone about this.

**Pull request merged**
