### PR TITLE
Update stream-classification-in-call-quality-dashboard.md

### PR DESCRIPTION
**Pull request by sjaligam-MS**
@GageAmes @Priteshkanani

### CODE REVIEW

**Comment by sjaligam-MS** [comment]
Audio Classifier needs updated formula due to SATIN codec changes

**Review by Priteshkanani — APPROVED** [review]

**Review by GageAmes — APPROVED** [review]

**Comment by sjaligam-MS** [comment]
@scanum : Please help in approving in this change.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by GageAmes** [comment]
I believe the correct contact here is @MicrosoftHeidi. Heidi--please see @scanum's comment.
> ...PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by GageAmes** [comment]
@MicrosoftHeidi Could you take a look at this and merge it if there are no issues?

**Comment by sjaligam-MS** [comment]
@scanum @MicrosoftHeidi - Please provide any updates here.

**Pull request merged**
