### PR TITLE
Update room-systems-v2-operations.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1461
Changed wording from 'image' to 'camera'

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@jambirk changes look correct. Could you please confirm and merge? Thanks!

**Comment by jambirk** [comment]
This is sample code meant to be copy/pasted to an admin console.  Why are we updating this?

**Comment by Travis-Snoozy** [comment]
That is not script logic I maintain. Take the following casual observations with grains of salt.

- #1461 notes **a logical OR**. The change, however **replaces** "Image" with "Camera" -- which will make all the previously-listed image devices no longer be listed, and only the camera devices show. This is **probably** not the behavior you want. 
- I don't know if the original intent of the script was to tag the video-ingest devices (which tend to be "image") or cameras (which tend to be "camera").
- I don't know if or how there may be changes between individual devices across Windows or driver versions.
- This just lists a bunch of devices. This does **not** speak to whether those devices are certified, or if they'll show up as cameras **to the app**. Using a logical OR will make more things show up, **but may also make invalid things show up**. That said, there is no guarantee from the current logic that any listed devices are certified or will show up, _however_, the ingest devices tend to be classed as "imaging"

**Comment by scanum** [comment]
@jambirk Hi James, following up on this. Thanks!

**Comment by jambirk** [comment]
This is an inadvisable change to the recommended commands. Closing the PR.

**Pull request closed without merging**
