### PR TITLE
fix example

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/10162

aligning to https://learn.microsoft.com/en-us/powershell/module/skype/new-csinboundblockednumberpattern?view=skype-ps and also tested

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by mkbond007** [comment]
@scanum Reviewing with the PM

**Comment by mkbond007** [comment]
@scanum @get-itips @JohanFreelancer9 The PM for this topic said, "We shouldn't make the change. Using ? at the beginning and $ at the end is the recommended guidance."

**Comment by get-itips** [comment]
> @scanum @get-itips @JohanFreelancer9 The PM for this topic said, "We shouldn't make the change. Using ? at the beginning and $ at the end is the recommended guidance."

Ok, closing.

**Pull request closed without merging**
