### PR TITLE
Update view-only-meeting-experience.md

### PR DESCRIPTION
**Pull request by bwilsonms**
Changing from will to might because when the banner is thrown it just means the infrastructure is being spun up.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@mkbond007 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by mkbond007** [comment]
@bwilsonms The "will" is explaining what the user experiences once the meeting has hit capacity and matches what the banner says. Is there a technical nuance that you want to call out?

**Comment by bwilsonms** [comment]
> @bwilsonms The "will" is explaining what the user experiences once the meeting has hit capacity and matches what the banner says. Is there a technical nuance that you want to call out?

The banner can be sent to producers/co-producers as soon as the infrastructure spins up to support view-only, will seems to indicate it will happen immediately when this banner is shown, this is not the case.

**Comment by scanum** [comment]
@mkbond007

**Pull request merged**
