### PR TITLE
Update music-on-hold.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8613.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
Not sure this is correct.  Please check with @JensTrier before we make this change.

**Comment by JensTrier** [comment]
Not sure we should make that change

Here the naming is Teams Phone https://docs.microsoft.com/en-us/microsoftteams/devices/phones-for-teams and https://docs.microsoft.com/en-us/microsoftteams/devices/phones-displays-deploy. But here it says Teams phone devices https://docs.microsoft.com/en-us/microsoftteams/devices/plan-device-deployment :-)

**Comment by CarolynRowe** [comment]
I agree with Jens on this one.  Let's not make this change.  Closing this one.

**Pull request closed without merging**
