### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3067 & #3066
Fixed 5 screenshots.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
I'm rejecting this one. First 4 images are dark theme - we don't use that for screen caps (use light theme).

5th one has nothing to do with the content.

**Comment by lindspea** [comment]
> I'm rejecting this one. First 4 images are dark theme - we don't use that for screen caps (use light theme).
> 5th one has nothing to do with the content.

Thanks @LolaJacobsen,  will ask them to correct the screenshots and will add them in another PR.

**Pull request closed without merging**
