### PR TITLE
Removing 404 link

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5879

Content has been removed also at source site https://www.edx.org/course/enabling-teamwork-with-microsoft-teams (404)

@LanaChin please review if we need to replace with another course (couldn't find one with the same title as a Microsoft resource)

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Thanks @get-itips. Looks like the link was updated recently to point to https://docs.microsoft.com/learn/paths/m365-manage-team-collaboration.  Closing this PR without merging.

**Comment by get-itips** [comment]
> Thanks @get-itips. Looks like the link was updated recently to point to https://docs.microsoft.com/learn/paths/m365-manage-team-collaboration. Closing this PR without merging.

Thanks to you @LanaChin

**Pull request closed without merging**
