### PR TITLE
Improving note

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6341

### CODE REVIEW

**Comment by get-itips** [comment]
@scanum This PR replaces https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6349 and was already copy-edited and ready to be merged.

**Comment by scanum** [comment]
@MSFTTracyP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@Kateyanne can you help getting this approved and merged?

**Comment by get-itips** [comment]
@MSFTTracyP Hello, can we merge this? Thank you!

**Review by MSFTTracyP — APPROVED** [review]
Thanks

**Pull request merged**
