### PR TITLE
Update guest-access.md

### PR DESCRIPTION
**Pull request by SignorelliDenis**
The same phrase was written two times.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SignorelliDenis Can you fix the conflicts for this Pull Request so that I can get this reviewed and merged?

**Comment by SignorelliDenis** [comment]
@AndreaBarr Done, but as far as I can see the line that was duplicated is already removed, probably by other other pull request.

**Comment by AndreaBarr** [comment]
@LolaJacobsen @tonysmit @chuckedmonson Can I merge this.

**Comment by tonysmit** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
