### PR TITLE
Removed Privacy Shield certification sentence in teams-privacy.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5642.

Source:
https://iapp.org/news/a/the-schrems-ii-decision-eu-us-data-transfers-in-question/

@MicrosoftHeidi could you kindly help me to confirm this information? Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MicrosoftHeidi** [comment]
This article cannot be changed without internal approval being competed. I'm checking with the correct resources now, but only internal resources can update this particular content.

**Comment by dariomws** [comment]
@MicrosoftHeidi sure thanks! Please confirm.

**Comment by dariomws** [comment]
Hi @MicrosoftHeidi, could you kindly let us know if there is any update here? Thank you!

**Comment by dariomws** [comment]
Hi @MicrosoftHeidi, could you kindly let us know if there is any update here? Thank you!

**Comment by MicrosoftHeidi** [comment]
I'm checking with our internal teams on this now, apologies for the delay.

**Comment by MicrosoftHeidi** [comment]
This will not be merged live, an update will be published with further information, but this is incorrect and should not be published.

**Pull request closed without merging**
