### PR TITLE
Clarify section

### PR DESCRIPTION
**Pull request by get-itips**
reordering sentences trying to make the section more clear

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8734

@ashishguptaiitb can you please review? Thank you

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@ashishguptaiitb PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@ashishguptaiitb Can you please review?

**Comment by ashishguptaiitb** [comment]
Thanks @get-itips for the suggestion. I have made this + other edits via a different PR. We shall publish it today and I shall then resolve this PR. Thanks for your patience.

**Comment by ashishguptaiitb** [comment]
Hi @get-itips , I've updated [the article](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users) as per the suggestions. Can you please check if it makes sense. Let me know and I shall close this PR without merging.

**Comment by get-itips** [comment]
> Hi @get-itips , I've updated [the article](https://docs.microsoft.com/en-us/microsoftteams/non-standard-users) as per the suggestions. Can you please check if it makes sense. Let me know and I shall close this PR without merging. (Hence, no need to resolve the conflicts in this PR.)

Yes, it makes sense, closing this one, thanks

**Pull request closed without merging**
