### PR TITLE
Added a comment for Edge RS2 using proxy to browser-support.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5156

@LolaJacobsen please, confirm this. I don't have access to https://portal.microsofticm.com. Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@nej-nej - ping.

**Comment by LolaJacobsen** [comment]
Pinging engineering managers referred by @nej-nej

**Pull request merged**
