### PR TITLE
Changing to Updated Software Revision

### PR DESCRIPTION
**Pull request by TokyoScarab**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3558

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
Not sure who submitted this request but the branch has conflicts.  I'm unable to merge.  Who submitted the request?

**Comment by CarolynRowe** [comment]
@TokyoScarab @JohanFreelancer9 @scanum 
Only @NMURAV or @FilippSe can make changes to this file.  Did the original request come from Nikolay or Filipp?

**Comment by CarolynRowe** [comment]
It looks like @TokyoScarab submitted this pull request.  Unless this request came from Nikolay or Filipp, I cannot merge.  Please note that this file is a legal document and can cause legal issues for Microsoft if it contains the wrong information.  This is why only @NMURAV or @FilippSe can request changes to this file.  I'm going to close this PR.  If we do want to make this change, Nikolay or Filipp can resubmit.  Thanks.

**Pull request closed without merging**
