### PR TITLE
Update manage-teams-in-modern-portal.md

### PR DESCRIPTION
**Pull request by MarcoCarampanta**
Following up on the footsteps of the file: "add-or-remove-an-emergency-address-for-your-organization.md" ; Adding troubleshooting steps for common scenarios, in this case, one driving multiple escalations on our SEE team in EMEA.

Already tested extensively, and verified with Graph team, also confirmed resolution on multiple cases.

note: the edits on lines #47 and #54 were an accident... -> don't know how to go back and edit them out.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@LolaJacobsen @tonysmit @chuckedmonson Can I merge this?

**Comment by kenwith** [comment]
@MarcoCarampanta - to edit out things like the - that were in lines 47 and 54 you can click the "Files Changed" tab and then click the pencil icon to edit the Pull Request. Then commit it directly to the same branch, which in this case is patch-7.   I can do it for you too if you want but wanted to let you know how to do it.

**Comment by kenwith** [comment]
Looks like lines 47 and 54 were already fixed though so. :)

**Comment by MarcoCarampanta** [comment]
Thanks for the tip :) 
Yeah I tried correcting #47 and #54, but wasn't seeing the latest commit with them in place, might've been my bad though! :) 


In regards to the "Known Issues" Article, according to the latest engagements I had up with the PG, this wasn't flagged as a "known issue" because supposedly that "note" in this current article was being used to justify the missing teams behavior.

Also, in my opinion it would make more sense for people who see this article THEN go test this feature straight away, then notice teams are missing and come back to the article to check on more info or fully read it, than someone who sees this article, or hears of the feature, goes there, and then searches for problems in the known issue article.

(as an alternative, we could perhaps submit an edit for the known issue article with this issue, then link the workaround back to this one, to the "troubleshooting" topic? - to avoid duplicating the steps)

**Comment by kenwith** [comment]
@MarcoCarampanta - makes sense to me, let's ask @LolaJacobsen who owns the article if we can go ahead and merge this one.

**Pull request merged**
