### PR TITLE
Corrected deleted channel retention

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3248

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
Please @LolaJacobsen review this pr, thanks.

**Comment by LolaJacobsen** [comment]
I asked PM to review today.

**Comment by LolaJacobsen** [comment]
I'm not merging this one. According to the PM, "Soft deleted channels are retained for 30 days prior to hard deleting them."

**Pull request closed without merging**
