### PR TITLE
Updated conference id digits reset-a-conference-id-for-a-user-in-teams.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4563

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tonysmit** [comment]
@dariomws - I'm going to merge this but I've created a feature request for engineering to look in to this. We need to know the default (confirm), add a setting to control the length on the bridge settings, and potentially an enable/disable toggle. Let's see what happens.

**Comment by tonysmit** [comment]
I'm checking with the PMs and will report back. @dariomws - do you think it would be a good feature to add: Adding the ability in Teams admin center for admins to be able to set static conf IDs or set the number of digits for conf ids. I ask because I've seen other feedback from customers that want this feature.

**Comment by dariomws** [comment]
Thank you @tonysmit.

I think adding the ability to set static conference IDs and set digits would be good. As you said, I´ve seen feedback from customers about it too.
Also, I think there are some plans to build it:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35772907-implement-the-ability-to-assign-static-meeting-ids

**Pull request merged**
