### PR TITLE
Fixed Sign In examples

### PR DESCRIPTION
**Pull request by pastperfect**
Changed "credentials" to "credential"

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@brandber can you merge? Thanks

**Comment by scanum** [comment]
@rajgodwin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
The changes in this PR have been made via a different PR. Closing this PR.

**Comment by tiburd** [comment]
cc: @scanum

**Pull request closed without merging**
