### PR TITLE
Update with-exchange-on-premises.md

### PR DESCRIPTION
**Pull request by gosepulv**
Adding specificity due to Remote Tenant PowerShell not allowing usage of Set-CsMeetingRoom with -LineUri parameter. If admin tries to perform phone number assignment using SfBO PowerShell:
"Unable to set LineUri. This parameter is restricted within Remote Tenant PowerShell..."
Raising awareness to this simple step (allowed when room accounts are configured in SfB Server as per https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/with-skype-for-business-server-2015) assists admins with overcoming the need to open support tickets, due to not being able to enable PSTN capabilities after accounts are enabled as rooms.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
@carolynblanding - can you tech review this change please?

**Review by carolynblanding — APPROVED** [review]
@dstrome remove PII change looks ok

**Pull request merged**
