### PR TITLE
Update phones-displays-deploy.md

### PR DESCRIPTION
**Pull request by kruthikaponnusamy**
Including Teams panels to the docs

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@HowlinWolf-92 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by kruthikaponnusamy** [comment]
Folks, has  this been approved? Can someone please publish this?
________________________________

**Comment by kruthikaponnusamy** [comment]
> @HowlinWolf-92 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

@HowlinWolf-92 @scanum Please help close this.

**Pull request merged**
