### PR TITLE
Update security-compliance-overview.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2561
Changed the wording as well as the link.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MicrosoftHeidi Hi Heidi! Could you please aid us with next steps? Thanks!

**Comment by scanum** [comment]
@MicrosoftHeidi Any updates on this? Thanks

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MicrosoftHeidi** [comment]
We aren't going to be referring to a third-party link, this is rejected.

**Pull request closed without merging**
