### PR TITLE
Add GPO issue code to new-teams-desktop-admin.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9884

### CODE REVIEW

**Comment by mosslive** [comment]
@dariomws : The explaining text is wrong. The problem is not, that a user cannot sign into the desired tenant, the reason is, that the login is restricted to certain tenants, this list could include the desired tenant.
E.g., I've experienced this at a client, whose Teams client is restricted to only sign into the company tenant. Works perfectly with the current client. But it blocks the appearance of the toggle button for testing the new Teams.
The message in the log file states: "Device is Sign-in restricted".

**Comment by dariomws** [comment]
@mosslive, if you restrict it to a specific tenant(s), it will allow you to connect to that tenant with the old client but you won't have the toggle to switch to the new tenant. Right?

**Comment by mosslive** [comment]
@dariomws Correct.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by JoanneHendrickson** [comment]
Closing this PR since this topic was split into different articles -- and this change is with content in the new-teams-troubleshooting-installation.md topic.  Added the new line there.

**Pull request closed without merging**
