### PR TITLE
Update plan-for-teams-live-events.md

### PR DESCRIPTION
**Pull request by bwilsonms**
Removing China specific details in regards to access.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@HowlinWolf-92 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by rjagiewich** [comment]
@scanum @HowlinWolf-92 is no longer with the company.

**Comment by tiburd** [comment]
@CarolynRowe 
THANK YOU!!

**Comment by tiburd** [comment]
@bwilsonms 
This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=main). We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Docs.
Thanks!

**Pull request merged**
