### PR TITLE
Update sfb-server-updates.md

### PR DESCRIPTION
**Pull request by erwinbierens**
added CU9 Skype for Business KB url
added CU8 hotfix 1 Skype for Business KB url

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@jambirk Hi James, changes look correct could you please review and merge? Thanks!

**Comment by scanum** [comment]
@jambirk Hi James, any updates on this? Thanks!

**Comment by jambirk** [comment]
@Ariantor this PR is for content you own, do you approve?

**Comment by scanum** [comment]
@Ariantor @SerdarSoysal Any updates on this? Thanks!

**Comment by jambirk** [comment]
Closing this. the March CU is for the Client, not the server, and the May update was pointing to the wrong kb. I'll resolve this issue in a separate PR.

**Pull request closed without merging**
