### PR TITLE
Update verbiage

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9327

### CODE REVIEW

**Comment by get-itips** [comment]
Not applying build suggestions at those are required in this case.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@brandber please review and merge. Thanks

**Comment by scanum** [comment]
@brandber PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@tiburd can you help me here? thank you

**Comment by get-itips** [comment]
@tiburd can you help me getting this merged please? thank you

**Comment by tiburd** [comment]
reviewed + confirmed

**Pull request merged**
