### PR TITLE
Updated links

### PR DESCRIPTION
**Pull request by nsshommo**
Link to the planning tool is updated.

### CODE REVIEW

**Comment by nsshommo** [comment]
@jambirk Can you merge it?

**Comment by jambirk** [comment]
Nassim, the extra padding in the See Also sections is being handled in bulk. The changes to the link you're requesting are not adequately explained: why is the  change more correct than what's already there?

**Comment by nsshommo** [comment]
@jambirk Thanks for your reply. From now, I will not edit the extra padding in the See Also section.

The present link goes to "Microsoft Lync Server 2013, Planning Tool" whereas it should go to "Skype for Business 2015, Planning Tool". That's why I have changed the link from "https://go.microsoft.com/fwlink/p/?LinkID=282725" to "https://www.microsoft.com/en-us/download/details.aspx?id=50357".

**Comment by jambirk** [comment]
in which case the correct action is to change the fwlink's target rather than hard code in another link. It's quite likely doing so will fix similar issues in other files. I've done so now that I understand what the issue was

**Pull request closed without merging**
