### PR TITLE
Correcting link

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7570

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@MicrosoftHeidi Can this please be merged? Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@MicrosoftHeidi Can this please be merged? Thank you

**Pull request merged**
