### PR TITLE
Career Coach - Screenshot update and content edits

### PR DESCRIPTION
**Pull request by jasonjgeiger**

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by jasonjgeiger** [comment]
@HowlinWolf-92, there appears to be a conflict now that another PR has been merged, but I don't permission to resolve the conflict. Both changes should be kept.

**Comment by HowlinWolf-92** [comment]
@jasonjgeiger I don't understand the underlines in your addition such as this one:

- __sections are required__

What's that about?

**Pull request merged**
