### PR TITLE
Added EXO Plan 1 license requirement for eDiscovery to Exchange-Teams-interact.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5845.

@dstrome @markjjo could you kindly help me to confirm this information?

"To use eDiscovery tools to search for and export Teams chat data for on-premises users, a minimum of an Exchange Online Plan 1 license is required."

### CODE REVIEW

**Comment by markjjo** [comment]
@dariomws From the topic that you link to about searching for Teams chat data for on-premises users: "The user whose primary mailbox is located in the on-premises organization must be assigned a Microsoft Teams license and a minimum of an Exchange Online Plan 1 license."

**Comment by dariomws** [comment]
@markjjo yes thank you! I want to double-check that information before this PR is merged.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
