### PR TITLE
Update teams-scoped-directory-search.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2152
Removed note about hybrid configurations.  Conflicting information between this article and https://docs.microsoft.com/en-us/microsoftteams/information-barriers-in-teams#required-licenses-and-permissions. Used latest article as correct info.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen changes look correct. Could you please confirm and merge? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen Any updates about this? Thanks

**Comment by SerdarSoysal** [comment]
@MicrosoftHeidi please review.

**Comment by SerdarSoysal** [comment]
@scanum please change the writer to @MicrosoftHeidi for this article.

**Comment by scanum** [comment]
@SerdarSoysal Lindsay has changed then author to Heidi. @MicrosoftHeidi Hi Heidi, PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Hi! Any updates on this? Thanks!

**Comment by MicrosoftHeidi** [comment]
This is correct, I will merge.

**Pull request merged**
