### PR TITLE
Need to update document to include Speed Dial

### PR DESCRIPTION
**Pull request by SamCosby**
Speed Dial isn't supported when you have an EXOP mailbox. Adding this blurb in here after confirming with the PO that this isn't supported.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
@carolynblanding - can you tech review this change?

**Comment by carolynblanding** [comment]
@dstrome This is not correct. Speed Dial entries can be from local contacts in Teams which does not rely on Exchange Online mailbox.

**Comment by dstrome** [comment]
Closing PR per tech review.

**Pull request closed without merging**
