### PR TITLE
Update get-clients.md

### PR DESCRIPTION
**Pull request by baardhermansen**
Added PowerShell code tag.
Updated the script a tiny bit; changed from testing length of $users to check for $null.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@voltarone @juturu please review this PR - let me know whether it's OK to merge.

**Comment by LolaJacobsen** [comment]
Ping'd PM in chat this morning.

**Comment by voltarone** [comment]
@juturu Please review the PR.  Thanks.

**Comment by LolaJacobsen** [comment]
Ping'd @juturu today.

**Pull request merged**
