### PR TITLE
Update integrate-with-exchange.md

### PR DESCRIPTION
**Pull request by Cloud-Writer**
The proposed changes to the Exchange UM Voice Mail row in the table and the note added below the table are requests from Senior PM Waseem Hashem. Please reword the text of the note as appropriate. Thanks!

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@MicrosoftHeidi Can I merge this?

**Comment by kenwith** [comment]
@CarolynRowe - Would you mind checking wording in this one since it references "Cloud Voice" .. does it look OK to merge?

**Comment by kenwith** [comment]
@Cloud-Writer - I checked with @CarolynRowe and the wording is "Cloud Voicemail" so this looks correct. One thing Carolyn wasn't sure about was the "Exchange UM Voice Mail" and if that should be changed to Cloud Voicemail. That was already in the article though so maybe worth checking on it in another task.

**Comment by CarolynRowe** [comment]
Sorry, I meant that Exchange UM Voice Mail should be Exchange UM Voicemail to be consistent. :-)

**Comment by tonysmit** [comment]
Agreed Carolyn. Exchange UM voicemail is very different from Cloud voice mail.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dariomws306** [comment]
Hi, it's true, Exchange UM Voicemail (online or onpremises) is different from Cloud Voicemail service. Even Exchange Online UM will be depreciated in the future and only Cloud Voicemail will be available.

But this Cloud Voicemail service is only supported on SfB Online and SfB Server 2019. I am fixing this.

**Pull request merged**
