### PR TITLE
Update cloud-video-interop.md

### PR DESCRIPTION
**Pull request by NancyForero**
Added a paragraph for GCC used in already public documentation https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#office-365-us-government-and-third-party-services

### CODE REVIEW

**Comment by NancyForero** [comment]
All checks passed and no conflicts with base branch

**Comment by NancyForero** [comment]
All checks passed and no conflicts with base branch

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
merging per PM Nancy Forero

**Pull request merged**
