### PR TITLE
Update plan-for-government-gcc.md

### PR DESCRIPTION
**Pull request by David-Rosenthal**
Updating Surface Hub status in GCC

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by David-Rosenthal** [comment]
> @nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

@scanum This is just updating a single line item on an existing table, to provide accurate information to customers. Can we get this approved and published?

**Comment by scanum** [comment]
@LolaJacobsen Changes look correct. Could you please review and merge? Thanks!

**Comment by SerdarSoysal** [comment]
@MicrosoftHeidi please follow-up.

**Comment by scanum** [comment]
@MicrosoftHeidi  PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
