### PR TITLE
Fixed Teams federation DNS requirements table in prepare-network.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5945.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MicrosoftHeidi** [comment]
Checking with internal resources before approving.

**Comment by dariomws** [comment]
@MicrosoftHeidi any update here? Thank you!

**Comment by dariomws** [comment]
Maybe @MSFTTracyP you can also help here. Thank you!

**Pull request merged**
