### PR TITLE
Remove old Singapore KYC form and replace it with new and correct one

### PR DESCRIPTION
**Pull request by debbylianto**
Hi team, 

The current new phone number request form (English) is obsolete and needs to be replaced with a correct KYC form for Singapore (English)

Old link: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/downloads/new-number-request-forms/new-phone-number-request-for-the-united-states-(v.5.0)-(en-us).pdf?raw=true

New SG KYC static link:  https://download.microsoft.com/download/e/9/5/e959053a-4b35-49f9-a23e-7085575c46f2/KYC-SG-EN.pdf Note: as this is the static link with new agreed name convention, there is no versions to it.

Please kindly approve and do let me know if you have enquiry. Thank you

Debby

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cazawideh 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by cazawideh** [comment]
Reassigning to @wlibebe, who is the contact for this topic

**Comment by debbylianto** [comment]
@cazawideh @wlibebe  The product owner is Chandra Kilaru chandra.kilaru@microsoft.com

**Comment by DaniEASmith** [comment]
@scanum I have reviewed and merged this PR.

**Pull request merged**
