### PR TITLE
Update direct-routing-enable-users.md

### PR DESCRIPTION
**Pull request by isrumnon**

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by FilippSe — APPROVED** [review]

**Comment by isrumnon** [comment]
Hi @FilippSe can we merge this PR?

**Comment by isrumnon** [comment]
Hi @FilippSe, reminder on getting this published

**Review by FilippSe — APPROVED** [review]

**Comment by isrumnon** [comment]
Hi @FilippSe when can we get this PR merged?

**Comment by isrumnon** [comment]
@scanum @JohanFreelancer9 any idea who would be able to merge this into prod?

**Comment by JohanFreelancer9** [comment]
@scanum, please assist to get this merged. Thanks.

**Comment by isrumnon** [comment]
Hi @scanum @yogkumgit can you help with getting this merged?

**Comment by JensTrier** [comment]
This has been updated in another PR

**Comment by isrumnon** [comment]
Thanks @JensTrier ! Can you share that PR? I'll close this one

**Pull request closed without merging**
