### PR TITLE
updating to teams

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8076

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@tiburd Can you help me getting this merged?

**Comment by get-itips** [comment]
@tiburd Can you help me getting this merged?

**Comment by tiburd** [comment]
Confirmed that update is correct. Merging this PR.

**Pull request merged**
