### PR TITLE
link not found

### PR DESCRIPTION
**Pull request by Divya-RP**
The hyperlink for Teams Essentials designed for small and mid-size businesses (SMB), pointing to https://www.microsoft.com/en-in/microsoft-365/blog/2021/12/01/new-microsoft-teams-essentials-is-built-for-small-businesses/ page is not found. Please correct the link

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — COMMENTED** [review]
@scanum, it seems that no changes have been made to this doc, so I do not think the issue raised has been resolved. Consequently, there is no copy to review.

**Comment by scanum** [comment]
Thank you @JohanFreelancer9 ! 

@Divya-RP Could you please review?

**Comment by Divya-RP** [comment]
Hi Team,

The link is invalid, it gives 404 error: Page not found - Microsoft 365 Blog<https://www.microsoft.com/en-in/microsoft-365/blog/2021/12/01/new-microsoft-teams-essentials-is-built-for-small-businesses/>

We need to add the correct link here.

Regards,
Divya

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
@Divya-RP - thank you for your submission. Could you please just edit the locale in the hyperlink and change it from "en-in" to "en-us", then it will work. Unfortunately, I cannot edit your PR. Many thanks.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Pull request closed without merging**
