### PR TITLE
Update browser-support.md

### PR DESCRIPTION
**Pull request by dariomws306**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3286

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
Checking with PM Neeraj Jain

**Comment by LolaJacobsen** [comment]
NOT merging, per PM. "it overly complicates our offerings."

**Comment by dariomws306** [comment]
Ok, but it works in this way. Is there some plan to change it?

image

**Pull request closed without merging**
