### PR TITLE
Clarify for GCC-H and DoD

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8711

image

@SerdarSoysal please review thank you

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@SerdarSoysal

**Comment by tiburd** [comment]
@chbalaki 
Hi,
Can you please review the change in this PR and let us know whether you agree with the change?
Thanks!

**Comment by get-itips** [comment]
@chbalaki

**Comment by get-itips** [comment]
@tiburd

**Comment by tiburd** [comment]
approved by @chbalaki via email.

**Pull request merged**
