### PR TITLE
Update skype-room-systems-v2.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2140
Updated Note.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Copy Edit

**Comment by scanum** [comment]
@tonysmit Changes look correct, could you please review and merge? Thanks!

**Comment by scanum** [comment]
@tonysmit Any updates on this? Thanks!

**Comment by tonysmit** [comment]
@Reeced40 - Hey. We shouldn't use the PS license SKU code, we need the names of the actual licenses that are on the marketing site and available to all. Can you please make that change and I will merge it. Thank you! Tony

**Comment by jambirk** [comment]
@sohailta how do we want this license referred to in docs?

**Comment by tonysmit** [comment]
@jambirk - this is one that you need to follow up on.

**Comment by tonysmit** [comment]
Checking with a PM. Will report back.

**Comment by tonysmit** [comment]
@Reeced40 - those licenses are only for volume licensing customers and aren't skus that we have available in other customer channels. In our docs, we write to those other channels and don't tailor it to volume licensing customers. I won't merge this so closing it out.

**Pull request closed without merging**
