### PR TITLE
Add Mexico to zone 1 or 2 in calling-plans-for-office-365.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9597.

### CODE REVIEW

**Comment by dariomws** [comment]
@CarolynRowe, could you help me to confirm if it's zone 2 for Mexico? Thanks!

**Comment by dariomws** [comment]
@DaniEASmith, I think this question is better for you:

Could you help me to confirm if it's zone 2 for Mexico? Thanks!

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by DaniEASmith** [comment]
Hey, @dariomws,

As it was explained to me by Chandra Kilaru, Mexico is its entirely own SKU. It isn't part of any zone. In this case, Mexico shouldn't be added to either zone list because if a customer wants Mexico Calling Plan PAYGo, they need to purchase the independent Mexico Calling Plan PAYGo license.

**Comment by dariomws** [comment]
@DaniEASmith, thanks! I think we can add a note with this information. Do you agree? I can add it using this PR.

**Comment by DaniEASmith** [comment]
> @DaniEASmith, thanks! I think we can add a note with this information. Do you agree? I can add it using this PR.

Yeah, I think that's a good idea.

**Comment by dariomws** [comment]
@DaniEASmith, done!

**Comment by DaniEASmith** [comment]
Looks good! I've merged.

**Pull request merged**
