### PR TITLE
Update direct-routing-enable-users.md

### PR DESCRIPTION
**Pull request by stvollet**
Hi Carolyne , I propose we get clearer on the user name . it requires the UPN not the display name. to this effect I suggest we mention the UPN in the example set-csUser - Identity "spencer.low@contoso.com" .... 
hope it helps.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by stvollet** [comment]
what is the next step ? shall I close this pull request ?

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
> what is the next step ? shall I close this pull request ?

Hi @stvollet, Carolyn needs to approve and merge the request. Thanks!

**Comment by stvollet** [comment]
ok but I see you completely missed my point as the doc didn't change you are still showing the user name and not the full UPN . From my tests it returns no value on my tenant unless I search for a spencer.low@contoso.com

**Comment by CarolynRowe** [comment]
I just merged the changes.  You received notification of the merge, but it takes awhile for the changes to show up on the live site.

**Pull request merged**
