### PR TITLE
Add .blog files to Media Logs section

### PR DESCRIPTION
**Pull request by havra**
Important files for troubleshooting calling issues:
Adding .blog files under skylib and media-stack folders.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen Changes look correct. Could you please review and merge? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen Changes look correct. Could you please review and merge? Thanks!

**Comment by LolaJacobsen** [comment]
I've ping'd PM TJ Singh to review this PR.

**Comment by LolaJacobsen** [comment]
OK per PM TJ Singh

**Pull request merged**
