### PR TITLE
Improve wording

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9678

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@dstrome

**Comment by scanum** [comment]
@dstrome
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@tiburd Can you please help me here? thanks

**Comment by tiburd** [comment]
sent email to @dstrome

**Comment by get-itips** [comment]
bumping on this one

**Comment by get-itips** [comment]
@tiburd any news? 👍

**Pull request merged**
