### PR TITLE
Update using-admin-roles.md  -- Clarify SfBO admins have some overlapping access with Teams admins

### PR DESCRIPTION
**Pull request by tomkau**
Making it clear that Skype for Business Online admins (not just Teams service admins) have access to all cmdlets in the Skype for Business PowerShell module.  We had one customer who thought it was a security bug.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by tomkau** [comment]
Hi @scanum, what is the process for merging the PR now that it is approved?  Thanks!

**Comment by LolaJacobsen** [comment]
@tomkau - feel free to ping me when you issue a PR for a Teams article. Otherwise, we catch them when we do our regular review of PRs (approximately weekly). I'm always happy to merge a PR on request.

**Comment by tomkau** [comment]
> @tomkau - feel free to ping me when you issue a PR for a Teams article. Otherwise, we catch them when we do our regular review of PRs (approximately weekly). I'm always happy to merge a PR on request.

Thanks @LolaJacobsen -- I wasn't aware of the regular review process.  I'll bear that in mind going forward!

**Pull request merged**
