### PR TITLE
Fixed maximum value for TMR expiration period

### LINKED ISSUE #8092: Incorrect maximum value for TMR expiration period in days
The documentation states 9,999 as max value whereas the `Set-CsTeamsMeetingPolicy` cmdlet documentation of attribute `NewMeetingRecordingExpirationDays` states 99,999 as max value.

[Teams cloud meeting recording > Frequently asked questions](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#frequently-asked-questions)
> #### How can an admin change the expiration date?
> Admins can change the default expiration setting in PowerShell or the Teams admin center before the feature is released. 
> [...] 
>
> The expiration days value can be set as follows:
> - Value can be from 1 to **_9,999_**.
> - Value can also be -1 to set TMR to never expire.

[Set-CsTeamsMeetingPolicy > Parameters: NewMeetingRecordingExpirationDays](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps#parameters)
-NewMeetingRecordingExpirationDays
Specifies the number of days before meeting recordings will expire and move to the recycle bin. Value can be from 1 to 99,999 days. Value can also be -1 to set meeting recordings to never expire.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

### PR DESCRIPTION
**Pull request by Markus-Hanisch**
fixes #8092 
The documentation states 9,999 as max value whereas the `Set-CsTeamsMeetingPolicy` cmdlet documentation of parameter `NewMeetingRecordingExpirationDays` states 99,999 as max value.

[Teams cloud meeting recording > Frequently asked questions](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#frequently-asked-questions)
> #### How can an admin change the expiration date?
> Admins can change the default expiration setting in PowerShell or the Teams admin center before the feature is released. 
> [...] 
>
> The expiration days value can be set as follows:
> - Value can be from 1 to **_9,999_**.
> - Value can also be -1 to set TMR to never expire.

[Set-CsTeamsMeetingPolicy > Parameters: NewMeetingRecordingExpirationDays](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps#parameters)
-NewMeetingRecordingExpirationDays
Specifies the number of days before meeting recordings will expire and move to the recycle bin. Value can be from 1 to 99,999 days. Value can also be -1 to set meeting recordings to never expire.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by Markus-Hanisch** [comment]
@scanum @tonysmit 
Any update on my PR?

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@CarolynRowe 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
This PR was submitted with branch conflicts. This article is currently undergoing major revisions by another writer. I've sent the link to the writer for consideration. Closing.

**Pull request closed without merging**
