### PR TITLE
fix cmdlet

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8290

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MikePlumleyMSFT** [comment]
@get-itips did you run a test on this? -Include All is a legit parameter for [Get-CsExternalAccessPolicy](https://docs.microsoft.com/en-us/powershell/module/skype/get-csexternalaccesspolicy?view=skype-ps#parameters).

**Comment by get-itips** [comment]
> @get-itips did you run a test on this? -Include All is a legit parameter for [Get-CsExternalAccessPolicy](https://docs.microsoft.com/en-us/powershell/module/skype/get-csexternalaccesspolicy?view=skype-ps#parameters).

Hello Mike @MikePlumleyMSFT , yes I did, this is with latest GA version (3.0.0), sorry the error is partly in spanish

image

**Comment by MikePlumleyMSFT** [comment]
Okay, thanks, @get-itips.

**Pull request merged**
