### PR TITLE
align statement

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9507

Currently, Teams channel section says

_Select the channel that you want to use (only **standard channels** are supported) and select **Apply**._

@DaniEASmith

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@DaniEASmith 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by DaniEASmith** [comment]
@get-itips @scanum @JohanFreelancer9 This version of the "Create a Phone System Call Queue" is the experimental version used in an A/B experiment. There's another version that 50% users may see as well, the non-experimental version. The file name of the other version is just "create-a-phone-system-call-queue.md" that should be updated with this change as well.

**Comment by get-itips** [comment]
@DaniEASmith good catch, done. Thanks

**Comment by get-itips** [comment]
@DaniEASmith can you help me resolving the file conflicts?

**Pull request merged**
