### PR TITLE
How many guests can I invite

### PR DESCRIPTION
**Pull request by naminakao**
Based on the following Article 1, Teams guest access makes use of Azure AD B2B collaboration capabilities. And Article 2 says you can invite up to 5 guest users for each paid Azure AD license to use your paid Azure AD services. 
I believe Microsoft Teams is not one of Azure AD paid services so users can invite more than 5 guest users for Teams.

Article 1:
Manage guest access in Microsoft Teams
https://docs.microsoft.com/en-us/microsoftteams/manage-guests
-------------
... Teams guest access makes use of Azure Active Directory business-to-business (B2B) collaboration capabilities....
-------------
Article 2:
Azure Active Directory B2B collaboration licensing guidance
https://docs.microsoft.com/en-us/azure/active-directory/b2b/licensing-guidance

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@naminakao There is a conflict in the pull request please correct it so I can have it reviewed

**Comment by kenwith** [comment]
@islubin - can you confirm the number of 'guests' that can be invited to Teams?

**Comment by kenwith** [comment]
@naminakao - thanks for content update, I fixed the conflict and will get confirmation to merge. Thanks for making docs better, much appreciated!

**Comment by islubin** [comment]
Tagging @somakbhattacharyya .  Teams is built on top of AAD, so the same restrictions for AAD apply to Teams.

**Comment by kenwith** [comment]
It looks like this change is change the Answer to: Q. How many guests can I invite?

FROM
A. You can add up to 5 guests per licensed user.

TO
A. No limitation.


Does this look OK to merge? @somakbhattacharyya

**Comment by kenwith** [comment]
@somakbhattacharyya - can you help approve this one?

**Comment by somakbhattacharyya** [comment]
@islubin is correct, AAD licensing still applies to Teams. We've called this out in the [article](https://docs.microsoft.com/en-us/microsoftteams/manage-guests) already 'If you plan to ask guest users to review their own access, read about guest user licensing. For more information, see Azure AD B2B collaboration licensing.'
The correct change will be to point to the same AAD document as the answer. So something like 'Teams doesn't restrict the number of guests you can add. However, the total number of guests that can be added to your tenant is based on what your AAD licensing allows. For more information, see [Azure AD B2B collaboration licensing](https://docs.microsoft.com/en-us/azure/active-directory/b2b/licensing-guidance).

**Comment by kenwith** [comment]
@dariomws306 - would you be able to update this PR as @somakbhattacharyya described above? Then we can get it merged into the doc.

**Comment by dariomws306** [comment]
@kenwith , I couldn't edit naminakao PR, I have created a new one: #1409

**Comment by kenwith** [comment]
Perfect, merged it. Thanks!

**Pull request closed without merging**
