### PR TITLE
Update Teams-overview.md

### PR DESCRIPTION
**Pull request by RaamAnalyst**
Added Prerequisites section with reference links to hardware requirements and specifications of Teams.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by SerdarSoysal** [comment]
@dstrome can you look at this and see if it fits with the overall direction we want for the landing page?

**Comment by tiburd** [comment]
Closing this PR due to age, inactivity, and conflicting files.

cc: @scanum

**Pull request closed without merging**
