### PR TITLE
Updating license

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7839

@SerdarSoysal please kindly review

Aligning to:

https://github.com/MicrosoftDocs/microsoft-365-docs/commit/05fd3c2558dd11891c02b7b8c29850a72dfed5d8 (recently updated)

also here

https://www.microsoft.com/es-ww/microsoft-365/enterprise/f1

https://www.microsoft.com/en-us/microsoft-365/enterprise/f3

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@SerdarSoysal Can you kindly ask for your review? Thank you

**Comment by get-itips** [comment]
@tiburd Can you help me getting this merged?

**Pull request merged**
