### PR TITLE
Updated link for Consumption Credit rates

### PR DESCRIPTION
**Pull request by benhopperau**
old link, update with new Teams page.

### CODE REVIEW

**Comment by kenwith** [comment]
@benhopperau - thanks for contributing to the content, much appreciated!  One note, it is best to remove the /en-us/ from the link so then the link will open in whatever the language is the person is using in their web browser. 

@LolaJacobsen and @CarolynRowe - let me know if link is correct and I can merge and remove the /en-us/. Thanks!

**Comment by benhopperau** [comment]
Thanks for the tip on the language, great to know!

I'll keep that in mind for future

**Comment by AndreaBarr** [comment]
@LolaJacobsen and @CarolynRowe Can I merge this?

**Comment by LolaJacobsen** [comment]
@CarolynRowe - this is your area.

**Comment by kenwith** [comment]
@benhopperau - confirmed with Lola and merged this one. One note is if you can remove the   en-us   on a PR that will let people in other locales have it load in their language. Thanks for your work on this, much appreciated!

**Pull request merged**
