### PR TITLE
Update Confusing Note

### PR DESCRIPTION
**Pull request by TokyoScarab**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2268

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by TokyoScarab** [comment]
I did not edit in that link, it was already there.  I was curious about the link and therefore trimmed away some of it to view the page it is from.  There exists only one link there which is the one included.
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/tree/live/Teams/downloads/emergency-calling

**Comment by scanum** [comment]
@CarolynRowe Changes look correct. Could you please review and merge? Thanks!

**Comment by scanum** [comment]
@CarolynRowe Changes look correct. Could you please review and merge? Thanks!

**Pull request merged**
