### PR TITLE
Update live-components-in-teams.md

### PR DESCRIPTION
**Pull request by lowong**
Updating Loop docs for better accuracy

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by lowong** [comment]
@scanum can you help merge this change?

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dstrome** [comment]
hi @lowong 

The file this PR changes, Teams/live-components-in-teams.md, was recently renamed to Teams/loop-components-in-teams.md. As a result, we're unable to accept this PR and need to close it. Please apply your changes to the file here - https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/blob/main/Teams/loop-components-in-teams.md - and submit a new PR.

Also, in the future, please use https://**review**.docs.microsoft.com when submitting contributions so that you are directed to our private repository. This will help speed up the contribution process for you.

Sorry for the inconvenience.

David.
CC @SerdarSoysal @scanum

**Pull request closed without merging**
