### PR TITLE
Update with-exchange-online.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2876
Added Powershell step.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@jambirk - please review

**Comment by jambirk** [comment]
Original comment was "In the section "Create an account and set Exchange properties" Step 1 the powershell should end with importing the PSSession:
Import-PSSession $sess -DisableNameChecking"

@chrisda and @sohailta do you agree with this addition? I don't see any problem but I'd defer to either of your expertise.

**Comment by chrisda** [comment]
The addition looks fine.

However, I would refrain from repeating the ExO PowerShell connection instructions in topics like this. Instead, I would simply link off to the official instructions: https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell.

One glaring issue I see is `Set-ExecutionPolicy Unrestricted`. This is a massive security hole that we should not espouse; `Set-ExecutionPolicy RemoteSigned` is what we require for ExO PowerShell, which is another reason to simply refer to the official connection instructions.

**Comment by jambirk** [comment]
@lindspea please address the concerns ChrisDa raised

**Comment by lindspea** [comment]
@jambirk @chrisda Thank you for the help. Just to confirm, although the addition is fine, it's recommended having it removed and rather adding a link in a note? @tseward fyi

**Comment by chrisda** [comment]
The addition is fine. I would change the first step to something like:

1. Connect to Exchange Online PowerShell. For instructions, see [Connect to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/connect-to-exchange-online-powershell).

In virtually all cases, that's the best move; there are too many variables with PowerShell these days (MFA? GCC High? etc.)

**Pull request merged**
