### PR TITLE
Add early media to teams-for-vdi.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7836.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by takataka365** [comment]
Thank you for considering updating the docs.
The "PSTN call ringback tone" limitation when using Teams with VDI does not seem to reflect the "Early Media" description on docs yet, when will this be reflected?

**Comment by scanum** [comment]
Hi @dstrome Hope all is well. Could you please help with this PR? thanks.

**Comment by scanum** [comment]
Hi @dstrome Wondering if you can help with this PR? Thanks.

**Comment by dariomws** [comment]
Hi @dstrome Hope all is well. Could you please help with this PR? thanks.

**Pull request closed without merging**
