### PR TITLE
Reflect current behavior

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9224

I tested this

I created a policy blocking "shared PowerApps" and assigned to a specific user

image

I could verify that, that user, cannot see shared Power Apps, even if the power app was shared with the user

image

but other users, that do not have this policy, can see 

image

So removing the sentence that conflicts with the next paragraph, user won't be able to request the app to the admin.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@ashishguptaiitb PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@ashishguptaiitb Can you please review so this PR can be merged? thanks

**Review by ashishguptaiitb — APPROVED** [review]
LGTM. Thanks.

**Comment by tiburd** [comment]
@get-itips 
Hi,
Do you agree that this PR is ready to merge?
Thanks!

**Comment by get-itips** [comment]
@tiburd yes, thanks!

**Pull request merged**
