### PR TITLE
select-rule wrong image

### PR DESCRIPTION
**Pull request by CarlosFarrica**
The image "select-rules.png" is wrong and should be changed. The option "setting" is not available anymore for customers. 
I have a case where the customer is complaining why the option is not available.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
Hi @dstrome Hope all is well. Could you please help with this PR? Thanks!

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request closed without merging**
