### PR TITLE
Update messaging-policies-in-teams.md

### PR DESCRIPTION
**Pull request by jambirk**
@LolaJacobsen  fleshed out the topic as discussed.

### CODE REVIEW

**Comment by jambirk** [comment]
@najacobo does this satisfy the broader audience need?

**Comment by LolaJacobsen** [comment]
@jambirk - I approved. Will wait for @najacobo before I merge.

**Comment by scanum** [comment]
@najacobo Any updates on this PR? PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by jambirk** [comment]
@scanum najacobo doesn't have merge permissions.

**Comment by najacobo** [comment]
> @najacobo does this satisfy the broader audience need?

This looks good to me! Thank you.

**Pull request merged**
