### PR TITLE
Update cloud-video-interop.md

### PR DESCRIPTION
**Pull request by NancyForero**
Add link and logo for latest CVI certified partner: Cisco

### CODE REVIEW

**Comment by NancyForero** [comment]
polycom
ciscocvi
Please replace the logo called polycom. png under /media with the first attached file.
Please add the second logo to /media under the name ciscocvi.png

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]
Copy is fine.

**Comment by NancyForero** [comment]
Could you please replace the ciscocvi.png that I had originally attached to the pull request with this version instead?
Thank you.

-Nancy
Microsoft Teams

**Comment by NancyForero** [comment]
ciscocvi
i see that the email did not attach the latest logo so attaching it mannually
.

**Comment by JohanFreelancer9** [comment]
@scanum Hi Manuela. I cannot replace the logo. can you please assist.

**Comment by NancyForero** [comment]
This is the latest png.

-Nancy
Microsoft Teams

**Comment by NancyForero** [comment]
ciscocvi
i hope you can see the latest png

**Comment by scanum** [comment]
I will need to assign this to a freelancer

**Comment by NancyForero** [comment]
Hello, what's the ETA for this to be published? Customer is asking. Thank you.

- Nancy

Microsoft Teams

Microsoft Teams

**Comment by NancyForero** [comment]
Hello, when can we have this pull request published? The customer is asking again. Thank you

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Monday, September 14, 2020 10:32 PM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Could you please replace the ciscocvi.png that I had originally attached to the pull request with this version instead?
Thank you.

-Nancy
Microsoft Teams

**Comment by NancyForero** [comment]
Hello, this change of adding a line and updating two icons is taking more than a week. How could we expedite this? Customer is very unhappy.

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Friday, September 18, 2020 11:03 AM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com>; 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <OfficeDocs-SkypeForBusiness@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>; Aravind Namasivayam <aravin@microsoft.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Hello, when can we have this pull request published? The customer is asking again. Thank you

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Monday, September 14, 2020 10:32 PM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com<mailto:OfficeDocs-SkypeForBusiness@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Could you please replace the ciscocvi.png that I had originally attached to the pull request with this version instead?
Thank you.

-Nancy
Microsoft Teams

**Comment by NancyForero** [comment]
### **Messages from customer on Teams that show his frustration:**

ciscoComplain

**Comment by NancyForero** [comment]
@JohanFreelancer9 2
@scanum 
**What is the blocker to commit this change so we can close on this? Thanks**

**Comment by NancyForero** [comment]
Hi @Serdar<mailto:Serdar.Soysal@microsoft.com>, could you help us unblock this PR? It has taken over a week to update one line and two logs and customer is extremely unhappy. Thank you.

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Monday, September 21, 2020 11:52 AM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com>; 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <OfficeDocs-SkypeForBusiness@noreply.github.com>; 'scanum@indexa.me' <scanum@indexa.me>
Cc: 'Author' <author@noreply.github.com>; Aravind Namasivayam <aravin@microsoft.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)
Importance: High

Hello, this change of adding a line and updating two icons is taking more than a week. How could we expedite this? Customer is very unhappy.

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Friday, September 18, 2020 11:03 AM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com<mailto:reply@reply.github.com>>; 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <OfficeDocs-SkypeForBusiness@noreply.github.com<mailto:OfficeDocs-SkypeForBusiness@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>; Aravind Namasivayam <aravin@microsoft.com<mailto:aravin@microsoft.com>>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Hello, when can we have this pull request published? The customer is asking again. Thank you

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Monday, September 14, 2020 10:32 PM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com<mailto:OfficeDocs-SkypeForBusiness@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Could you please replace the ciscocvi.png that I had originally attached to the pull request with this version instead?
Thank you.

-Nancy
Microsoft Teams

**Comment by SerdarSoysal** [comment]
@scanum @NancyForero : I'm on this.

**Comment by serdar** [comment]
Hi Nancy
You’ve tagged the wrong Serdar on this PR, I don’t work at Microsoft (yet) :)

On 22 Sep 2020, at 6:46 am, NancyForero <notifications@github.com> wrote:

﻿

Hi @Serdar<mailto:Serdar.Soysal@microsoft.com>, could you help us unblock this PR? It has taken over a week to update one line and two logs and customer is extremely unhappy. Thank you.

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Monday, September 21, 2020 11:52 AM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com>; 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <OfficeDocs-SkypeForBusiness@noreply.github.com>; 'scanum@indexa.me' <scanum@indexa.me>
Cc: 'Author' <author@noreply.github.com>; Aravind Namasivayam <aravin@microsoft.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)
Importance: High

Hello, this change of adding a line and updating two icons is taking more than a week. How could we expedite this? Customer is very unhappy.

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Friday, September 18, 2020 11:03 AM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com<mailto:reply@reply.github.com>>; 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <OfficeDocs-SkypeForBusiness@noreply.github.com<mailto:OfficeDocs-SkypeForBusiness@noreply.github.com>>
Cc: 'Author' <author@noreply.github.com<mailto:author@noreply.github.com>>; Aravind Namasivayam <aravin@microsoft.com<mailto:aravin@microsoft.com>>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Hello, when can we have this pull request published? The customer is asking again. Thank you

-Nancy
Microsoft Teams

From: Nancy Forero
Sent: Monday, September 14, 2020 10:32 PM
To: 'MicrosoftDocs/OfficeDocs-SkypeForBusiness' <reply@reply.github.com<mailto:reply@reply.github.com>>; MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com<mailto:OfficeDocs-SkypeForBusiness@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update cloud-video-interop.md (#5758)

Could you please replace the ciscocvi.png that I had originally attached to the pull request with this version instead?
Thank you.

-Nancy
Microsoft Teams

**Comment by SerdarSoysal** [comment]
Closing this PR. Will make this change in the private repo.

**Pull request closed without merging**
