### PR TITLE
DO NOT MERGE: Update user-activity-report.md

### PR DESCRIPTION
**Pull request by quentinhurdazure**
@LolaJacobsen this is not ready to go live, but we needed the PR ready so we can share a preview.  is there any other preview mech we can use to share with others who don't have github?  

cc: @LanaChin @MicrosoftHeidi

### CODE REVIEW

**Comment by quentinhurdazure** [comment]
ensuring we are in draft mode

**Comment by tonysmit** [comment]
@scanum - This one needs copy edited please. There are grammatical issues. Please **DON'T MERGE** those changes!!

**Comment by tonysmit** [comment]
@scanum - this needs a copy edit. DON'T MERGE those changes please.

**Comment by tonysmit** [comment]
@scanum - this PR needs a copy edit. Please DON'T MERGE those changes. Thanks, Tony

**Pull request merged**
