### PR TITLE
Additional Basic Client Limitation

### PR DESCRIPTION
**Pull request by v-ancoll**
Support identify addition Basic client limitation

### CODE REVIEW

**Comment by kenwith** [comment]
@v-ancoll - thanks for updates!

@jambirk - OK to merge?

**Comment by jambirk** [comment]
Need an okay from @PhillipGarding   on this topic before we approve

**Comment by PhillipGarding** [comment]
I can’t tell what topic this is trying to modify.  I also don’t know whether this is accurate.  The wording doesn’t seem like it describes things in normal terminology (using abbreviations, etc.)

Phil.

**Comment by kenwith** [comment]
@PhillipGarding - you can click on the "Files changed" button at the top and see the changes in green. Anything in red is being removed and anything in green is being added. On this one a sentence is being added. That "Files changed" button will also show the exact file being changed and the path. Here is a direct link: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/1136/files

**Comment by kenwith** [comment]
@jambirk - you might want to do a quick edit copy too. Here is the sentence: "Miss call notification emails are not generated when user is UM disabled and legacy Outlook Client (2013 or earlier) is used".

I would copy edit it to:

"Missed call notification emails are not generated when a user status is UM disabled and they are using a legacy Outlook Client (2013 or earlier)."

**Comment by kenwith** [comment]
@v-ancoll - just wanted to say we really appreciate you taking the time to make the docs better too and capture the knowledge you are discovering when working with the products. We really appreciate it and the community appreciates it too.

**Comment by v-ancoll** [comment]
Hello all,

Thank you so much for your feedback, and also was a pleasure to helping the community ;)

Have a great day.

Kind Regards,

**Pull request merged**
