### PR TITLE
Corrections into Format,

### PR DESCRIPTION
**Pull request by j0rt3g4**
Pending corrections on LINKS

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin Changes look correct. Could you please review and merge? Thanks!

**Comment by LanaChin** [comment]
@shars - over to you

**Comment by SharS** [comment]
Merged and closed.

**Pull request merged**
