### PR TITLE
Solving Issue #3184

### PR DESCRIPTION
**Pull request by j0rt3g4**
Adding last 3 missing updates on table #3184

### CODE REVIEW

**Comment by j0rt3g4** [comment]
Copy review @nenonix @JohanFreelancer9 is required on this one guys. Thank you in advance!

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@PhillipGarding PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by satvirr** [comment]
@scanum Phil has left the company. Updating this page with the latest KB article is not the correct solution here. We need to link this out to the pages that mainatain the KB articles already. 

For 2016 client: 
https://support.microsoft.com/en-us/help/3123065/how-to-obtain-the-latest-update-for-skype-for-business-2016

For 2015/2013 client: 
https://support.microsoft.com/en-gb/help/2998606/how-to-obtain-the-latest-update-for-skype-for-business-2015-lync-2013

here's a pull request that I created that has this change:

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/3395

but I have not made a change to github before so not sure how to commit it.

**Comment by scanum** [comment]
@j0rt3g4 Can you please help me add these links? Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Hi Serdar! Hope you are doing well. Wondering who we should add as an author instead of Phillip Garding? Thanks!

**Pull request merged**
