### PR TITLE
Updates on Image #2895

### PR DESCRIPTION
**Pull request by j0rt3g4**
Adding new Graphics and sources on Issue #2895

### CODE REVIEW

**Comment by j0rt3g4** [comment]
Solving Issue #2895

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@LanaChin Hi Lana, following up on this PR. Please let me know if there are any updates. Thanks

**Comment by LanaChin** [comment]
The text in the image is too hard to read.  Please submit an art request to re-create the image. Thank you.

**Comment by j0rt3g4** [comment]
Hi @LanaChin On the Onedrive are the sources of both .VS and .PDF
https://onedrive.live.com/redir?resid=5FC5BC3B89F7C2C0!382873&authkey=!AHlVOgkt8BmRl4M&e=bDSYTm

**Comment by LanaChin** [comment]
@j0rt3g4 , @scanum - please check with neonix on the art guidelines. The image needs to be re-created so that the text is clear and easy to read. Thanks.

**Comment by j0rt3g4** [comment]
@nenonix  The images and the VS are on the onedrive above. Would you please be son kind in checking it?

**Comment by scanum** [comment]
@nenonix Hi Nicole, could you help out on this? Thanks!!

**Comment by LanaChin** [comment]
hi @nenonix, @scanum - any updates on having this image redone?  Thank you

**Comment by LanaChin** [comment]
@scanum - assigned this back over to you. thank you.

**Comment by j0rt3g4** [comment]
@nenonix Please what would be the guidelines or how can I change it to align it?

**Comment by scanum** [comment]
@JohanFreelancer9 Hi Johan! Is this something that you maybe can help us with? Thanks!

**Comment by JohanFreelancer9** [comment]
@scanum Hi Manuella. I am sorry but I cannot be of much help when it comes to images and artwork.

**Pull request merged**
