### PR TITLE
Add fully support for Firefox to browser-support.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8650.

@dstrome, could you kindly confirm that we can add this information to the article? Thanks!

Source:
https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=83838

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
@dstrome @npherson, do you think you can help here? I cannot find the message center and roadmap announcements anymore, so I think Firefox and Safari 1:1 call full support is not available yet. Thanks!

**Pull request closed without merging**
