### PR TITLE
Add QER Power BI template

### PR DESCRIPTION
**Pull request by MattWade-MS**
Add information on the QER template to the list of CQD Power BI templates.  Also removed the "NEW" marker for AA/CQ and Utilization reports as these have been out for over a year now.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MattWade-MS** [comment]
Any update on when this will be completed?

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by MattWade-MS** [comment]
Hello, is there an expected timeline for this merge to be completed?  This merge is part of a larger project I'm working on and need to get this published so I can meet the EOY goals. Thank you.

**Comment by MattWade-MS** [comment]
Any updates?  This has been pending for some time now.

**Comment by JohanFreelancer9** [comment]
@scanum, please help to get this merged. Thanks.

**Comment by MattWade-MS** [comment]
Can someone please help get this merged?  It's bee a few weeks now.

**Pull request merged**
