### PR TITLE
Update back-end-server.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1720
Updated SFB server 2019 supported SQL AlwaysOn editions/versions

### CODE REVIEW

**Comment by scanum** [comment]
@SerdarSoysal Hi Serdar, changes look correct. Could you please check and merge? Thanks

**Comment by scanum** [comment]
@SerdarSoysal Hi Serdar! Just following up on this PR. Could you please check and merge? Thanks.

**Comment by SerdarSoysal** [comment]
@microsoftheidi please review.

**Comment by scanum** [comment]
@MicrosoftHeidi Hi Heidi, any updates on this issue?

**Comment by MicrosoftHeidi** [comment]
This is pending review, and I have no timeline for that.

**Comment by MicrosoftHeidi** [comment]
This should not be merged, and was handled in a different update request. These changes would now clash, and the article as it is today should be correct.

**Pull request closed without merging**
