### PR TITLE
Replaced magic whiteboard image transparency with white background

### PR DESCRIPTION
**Pull request by get-itips**
Replaced magic whiteboard image transparency with white background so it is rendered ok in Docs Dark Mode

Reason behind more than one commit is because i used wrong username in git config and fixed.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@get-itips Andres, can you help me by changing the author to Ken? Thanks!

**Comment by scanum** [comment]
@get-itips Andres, can you help me by changing the author to Ken? Thanks!

**Comment by get-itips** [comment]
> @get-itips Andres, can you help me by changing the author to Ken? Thanks!

there you go

**Comment by scanum** [comment]
@kenwith Hi Ken! PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by kenwith** [comment]
I went ahead and merged this for @SerdarSoysal . He will be taking ownership of James articles going forward though.

**Pull request merged**
