### PR TITLE
Update clarification sentence of support

### PR DESCRIPTION
**Pull request by NancyForero**
Update clarification sentence of support

### CODE REVIEW

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by NancyForero** [comment]
Hello, when will this be published? Thanks.

**Comment by JohanFreelancer9** [comment]
@scanum

**Comment by scanum** [comment]
@tiburd hi Tina! Hope all is well. Could you please help us with this PR? TY

**Comment by tiburd** [comment]
@NancyForero 
Hi,

This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main). We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Learn.

Also, at your earliest convenience, please complete your account setup so that your GitHub and Microsoft accounts are connected:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

Thanks!

**Pull request merged**
