### PR TITLE
Update azure-monitor-deploy.md

### PR DESCRIPTION
**Pull request by Reeced40**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7161
Fixed ID's

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dstrome Hope you are well. Wanted to follow up here to see if there is an update? Please let us know if there is anything we can do to help. Thanks.

**Comment by tiburd** [comment]
@dstrome or @Turgayo 
Please review. Thanks!

**Comment by tiburd** [comment]
Closing PR; changes made in a different PR.

cc: @scanum

**Pull request closed without merging**
