### PR TITLE
Change CU8 --> CU7 for Business Server

### PR DESCRIPTION
**Pull request by khorne3**
CU7 appears to be the most recent CU for Skype for Business Server 2015.

### CODE REVIEW

**Comment by kenwith** [comment]
@khorne3 - thanks for making the content better, much appreciated!

@lsomi - OK to merge?

**Comment by kenwith** [comment]
@khorne3 - I confirmed that CU8 is required for upgrading to Teams. Is that not your understanding?

**Comment by LolaJacobsen** [comment]
@bjwhalen - OK to merge?

**Comment by bjwhalen** [comment]
NO!  this is wrong. do not merge this.   CU 8 is coming out this month. it was supposed to be out in OCtober so I posted it then, but it got delayed to December.  Just leave this as is, DO NOT MERGE

**Comment by kenwith** [comment]
@khorne3 - I think we confirmed that CU 8 is coming out and it will be required for upgrading to Teams directly. Thanks for your contribution and helping to make the docs better. Keep the updates coming based on your experience!

**Pull request closed without merging**
