### PR TITLE
[DO NOT MERGE] SEO edits firstline-workers-quickstart

### PR DESCRIPTION
**Pull request by jdmartinez36**
Edited metadata title to align with other quick start guides. Description edited to include keywords. Sentence added to introduction to add keywords.

Most of the additions are placed in a way that offers a definition of what a Firstline Worker is.

@DaniHalfin

### CODE REVIEW

**Comment by DaniHalfin** [comment]
I'm reviewing. Thanks.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@DaniHalfin Hi! Is this PR going to be closed? Thanks!

**Comment by tuco-ulf** [comment]
@DaniHalfin can we get Kensington Schmidt to review this one?

**Comment by DaniHalfin** [comment]
I've reached out a few times now. Will reach out again.

**Comment by scanum** [comment]
@DaniHalfin any updates here? thanks!

**Comment by DaniHalfin** [comment]
Following up one last time and will close if nothing comes of it.

**Pull request merged**
