### PR TITLE
Update teams-security-guide.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4369
Removed wording.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MicrosoftHeidi** [comment]
@MSFTTracyP can you confirm this won't overwrite more recent changes to this article? Thanks!

**Comment by MSFTTracyP** [comment]
Done sep.

**Pull request closed without merging**
