### PR TITLE
Fixed uninstall methods on teams-for-vdi.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4585

The script was removed 2 months ago:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/e3b56d74f88d7af82534a069e8e979af1663959e
And the article was replaced by https://docs.microsoft.com/microsoftteams/msi-deployment. I think we cannot remove MSI from VDI using this method.

Could you confirm @LolaJacobsen @LanaChin? Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LanaChin** [comment]
This issue has also been reported in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4179.

**Comment by LanaChin** [comment]
Following up with the PM.

**Comment by LanaChin** [comment]
Looks great, @dariomws. Merged.

**Pull request merged**
