### PR TITLE
Picture refered to is missing

### PR DESCRIPTION
**Pull request by StaleHansen**
The Restrictions to dial-outs options

shows up like this, so should either be removed or made sure the picture works

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tonysmit** [comment]
@scanum - This is bug in the build process. Let me check on the status. The path is correct and the file is in the repo.

**Comment by tonysmit** [comment]
@LanaChin - Can you please republish this topic? I checked an the PNG is available and the link is correct. Apparently if you republish it, it should fix this issue. Thanks! Tony

**Pull request closed without merging**
