### PR TITLE
AudioCodes M1000B is incorrect

### PR DESCRIPTION
**Pull request by leeford**
Speaking with AudioCodes UK, the Mediant 1000B does not currently support Media Bypass, so I have changed back to "Pending".

### CODE REVIEW

**Comment by scanum** [comment]
@NMuravlyannikov @CarolynRowe Hi! Changes look correct. Could you please check and merge? Thanks

**Comment by CarolynRowe** [comment]
Hello,
Changes to this file require approval by  Nikolay.  We have sent the request on to the product team for approval.

**Comment by jambirk** [comment]
@NMuravlyannikov do you approve this change?  "Speaking with AudioCodes UK, the Mediant 1000B does not currently support Media Bypass, so I have changed back to "Pending"."

**Comment by NMURAV** [comment]
Yes please

**Pull request merged**
