### PR TITLE
Updated Ribbon SBC supported version per agreement with Ribbon

### PR DESCRIPTION
**Pull request by FilippSe**
Updated Ribbon SBC supported version per agreement with Ribbon and validation on our side

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.
--

**Comment by FilippSe** [comment]
I still see the older version and unresolved conflict. What is the issue? I just changed version value from 6.2 to 7.2, there should not be any other changes

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
I'm sorry, but I do not know how to resolve the conflicts.  I want to make sure we don't publish the wrong info.  Filipp, I think we need to close this PR and submit another one.  Or, I'll make the change in my own branch and publish.  So, just to clarify...   Under Ribbon Communications, change V6.2 to V7.2?

**Comment by FilippSe** [comment]
Hi
Yes, only change is from 6.2 to 7.2 for Ribbon.

Best regards,

Filipp Seljanko
Senior Program Manager, Microsoft
Email: filippse@microsoft.com<mailto:filippse@microsoft.com>

**Comment by CarolynRowe** [comment]
Made changes in another branch.  Will go live today.  Closing this PR because of merge conflicts.

**Pull request closed without merging**
