### PR TITLE
Updating VDI Support note

### PR DESCRIPTION
**Pull request by get-itips**
Updating VDI Support note https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1062

### CODE REVIEW

**Comment by kenwith** [comment]
I believe @LanaChin is working on VDI right now. @LanaChin - OK to merge this and it fits in with what you are working on? Looks OK to me.

**Comment by scanum** [comment]
@LanaChin Hi Lana, could you please check and approve to be merged? Thanks!

**Comment by LanaChin** [comment]
@scanum, @get-itips - I reached out to the PM who confirmed that the current statement should not be changed. The links are partner implementations, not supported by Microsoft.

**Comment by scanum** [comment]
@LanaChin Hi Lana! Thank you for the update. Could you please close this PR? Thanks!

**Pull request closed without merging**
