### PR TITLE
Update audio-conferencing-common-questions.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3706

### CODE REVIEW

**Comment by scanum** [comment]
@dariomws306 @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@tonysmit 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tonysmit** [comment]
@dariomws - changing the links to /Skype/SFBOnline is incorrect. We don't even have a repo or docset for "Skype". I'm incorping the reset PIN change but not changing all of the links. I tested the links and all of them worked for me. However, I'm removing all of the Skype for Business links anyway.

**Comment by dariomws** [comment]
Hi @tonysmit, sorry but I don't understand. I changed the links to relative location in the same repo (OfficeDocs-SkypeForBusiness) because if you clicked on them before on Github you got 404. They worked on docs but not in Github.
I put the relative real location:
image
image

I this way links will work on Github and docs. Maybe I'm wrong.

**Comment by tonysmit** [comment]
Hey Dario. Yes, there are different URLs to use. However, in the docs we use relative “doc” URLs if they are not in the same repo, in this case they are but we don’t use the Repo path. That’s just for Github.  Thanks, Tony

**Comment by tonysmit** [comment]
I will make the changes to the doc about the Resetting the PIN though. :)

**Pull request closed without merging**
