### PR TITLE
Delete phone-system-voicemail.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Content has been migrated to MS teams file. And this file holds no content now.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by nenonix** [comment]
@sowjanya365 please fix the conflict,. Did you also change the TOC and follow procedure for deleting/changing a file?

**Comment by sowjanya365** [comment]
Hi @nenonix 

I've checked the TOC and inbound links. No conflicts found. Thank you so much for all your help on this. Great coordination!

**Comment by sowjanya365** [comment]
Hi @scanum 

Please let me know if there is anything pending my side? Thank you.

**Comment by scanum** [comment]
@tonysmit Hi Tony! Changes look correct. Could you please review and merge? Thanks!

**Comment by tonysmit** [comment]
I couldn't merge this request. If it's still an issue, please let me know. Thanks.

**Comment by tonysmit** [comment]
@CarolynRowe - I don't know what is going on here. Can you please investigate or had this off to a vendor to investigate. The first link shows that the content is completely blank. Thanks.

**Comment by CarolynRowe** [comment]
I have followed up with @SharS.  We need to redirect that link to the Teams live file.  Thank you.

**Comment by SharS** [comment]
This problem has been fixed. Thanks for catching this.

**Pull request closed without merging**
