### PR TITLE
Update location-based-routing-configure-network-settings.md

### PR DESCRIPTION
**Pull request by sowjanya365**
issue #1552 - IPAddress has been corrected now.

### CODE REVIEW

**Comment by scanum** [comment]
@LanaChin Hi Lana, changes look correct. Could you please confirm and merge? Thanks!

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin Any updates on this? Thanks!

**Comment by LanaChin** [comment]
@scanum I confirmed with the PM and merged the change. Thanks.

**Pull request merged**
