### PR TITLE
add new release

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8390

### CODE REVIEW

**Comment by get-itips** [comment]
@tiburd who should we ask review on this one? :)

**Comment by tiburd** [comment]
@rajgodwin 
Please review this PR, and merge if you approve.
Thanks!

**Comment by get-itips** [comment]
@rajgodwin Can you please review this? thank you

**Comment by get-itips** [comment]
article was updated in another PR

**Pull request closed without merging**
