### PR TITLE
Update direct-routing-plan-media-bypass.md

### PR DESCRIPTION
**Pull request by ThomasBIDAULT**
In Media Bypass environment client reaches directly SBC public IP using its media port define in the meeting settings (by default 50 000 to 50 019)

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
Before merging this PR, we should get sign off from @FilippSe.

**Comment by CarolynRowe** [comment]
The PM has requested that we not merge this change.  We are following up on the correct port ranges.  I am closing this PR for now to ensure we do not accidentally merge.

**Pull request closed without merging**
