### PR TITLE
Update direct-routing-plan.md

### PR DESCRIPTION
**Pull request by dlau38**
Adding new Oracle Communication SBC to the supported SBC list.

### CODE REVIEW

**Comment by kenwith** [comment]
@dlau38 - thanks for adding to the content, much appreciated! Are you with the product team or how did you get the information regarding this new entry?

**Comment by CarolynRowe** [comment]
Thank you for your feedback.  It has been forwarded to the product team.  Up-to-date information about SBCs supported with Direct Routing can be found here:  https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-border-controllers.

**Comment by dlau38** [comment]
> @dlau38 - thanks for adding to the content, much appreciated! Are you with the product team or how did you get the information regarding this new entry?

HI Ken, I work for Oracle and know that we have just got included as part of the MS Teams SBC.

**Comment by CarolynRowe** [comment]
Thanks, David.  We are removing this information from the plan doc and pointing users to the supported SBCs list.  The supported SBCs list is the one place everyone should go for information about supported SBCs.

**Pull request closed without merging**
