### PR TITLE
Removing SfB Admin center instructions

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6311

@tonysmit do you agree on removing this?  Thank you

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
Hello, can this PR be reviewed and merged? Thank you!

**Comment by scanum** [comment]
@tonysmit Following up on the status of this PR, thank you!

**Pull request merged**
