### PR TITLE
Clarifying Org-wide Custom App Setting

### PR DESCRIPTION
**Pull request by TokyoScarab**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4140

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Investigating.

**Comment by TokyoScarab** [comment]
Just following up on this. Thanks!

**Comment by TokyoScarab** [comment]
@LanaChin Any news?

**Pull request merged**
