### PR TITLE
Update console.md

### PR DESCRIPTION
**Pull request by jambirk**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/1982 

@Travis-Snoozy do you agree with this change?

### CODE REVIEW

**Comment by jambirk** [comment]
Please hold this PR until Travis signs off.

**Comment by Travis-Snoozy** [comment]
Sorry, I know it's tangential, but can we also remove the warning about the space that precedes the tip that was just added? The issue with there being a space in the path has been fixed since the release of version 1.4.3 of the script. :)

**Comment by Travis-Snoozy** [comment]
The "tip" trails off with "Make sure to run the" as the final sentence.

**Comment by jambirk** [comment]
Just fixed both issues Travis pointed out. I will merge this PR later today unless Travis asks for a delay.

**Pull request merged**
