### PR TITLE
Updated superscript in using-admin-roles.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6407.

### CODE REVIEW

**Comment by dariomws** [comment]
@SharS are you agree with this update? Thanks!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by SerdarSoysal** [comment]
@dariomws instead of saying "the latest release" can you please specify the specific version? So we can then say "version X or later".

**Comment by dariomws** [comment]
@SerdarSoysal done!

I've copied that sentence from the following article:
https://docs.microsoft.com/microsoftteams/teams-powershell-overview#manage-teams-with-powershell

I proposed an update there too:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6805

If you want, I can check for more articles. I think there are some cmdlets with the same sentence.

Thanks!

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request merged**
