### PR TITLE
Update manage-resource-accounts.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3650
Added to important note.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.
--

**Comment by rjagiewich** [comment]
Hi @dstrome - per our convo today, will you review this PR? Thanks!

**Comment by dstrome** [comment]
hi @lindspea - can you please select the "Allow edits from maintainers" checkbox on this PR? It should be in the right-hand column at the bottom. Specific instructions here - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks.

**Comment by lindspea** [comment]
> hi @lindspea - can you please select the "Allow edits from maintainers" checkbox on this PR? It should be in the right-hand column at the bottom. Specific instructions here - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> Thanks.

Done.

**Pull request merged**
