### PR TITLE
update note

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2826

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@LanaChin  Hi! Following up on this issue, please let me know if there is anything I can do to help!.

**Comment by LanaChin** [comment]
Reached out to PM for review.

**Comment by scanum** [comment]
@LanaChin Hi Lana, any updates? Thanks!

**Comment by LanaChin** [comment]
Bumped the thread to the PMs.

**Pull request merged**
