### PR TITLE
Update Teams-add-in-for-Outlook.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #2096 - Removed the available features.

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
I've asked the Meetings PM group to review this PR. I suspect other aspects of the Other considerations section of this article may also be out-of-date.

**Comment by LolaJacobsen** [comment]
Ping'd the PM again.

**Comment by LolaJacobsen** [comment]
@sonu-arora - please review.

**Pull request merged**
