### PR TITLE
Add max number of simultaneous active calls

### PR DESCRIPTION
**Pull request by mdressman**
Added detail about maximum number of active calls limit. A customer faced this issue and could not find this limit documented.

### CODE REVIEW

**Comment by scanum** [comment]
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by gregorybrunn** [comment]
@MicrosoftHeidi any update on when this will be merged and public customers are asking a bunch and want to see the documentation

#Sign-off #sign-off

**Comment by MicrosoftHeidi** [comment]
This article needs additional approvals before any change can be submitted, do not merge this change.

**Comment by gregorybrunn** [comment]
@MicrosoftHeidi any luck on getting the approves to agree to cahnge.
@sign-off

**Pull request merged**
