### PR TITLE
Update virtual-user.md

### PR DESCRIPTION
**Pull request by msbemba**
Business premium and essential do not have phone system add on..Made the changes in note

### CODE REVIEW

**Comment by jambirk** [comment]
@waseemhashem must approve this PR before it can be merged.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by jambirk** [comment]
@waseemhashem must approve this PR before it can be merged.

**Comment by waseemhashem** [comment]
I approve, go ahead and publish.

**Comment by jambirk** [comment]
addresses https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2773

**Pull request merged**
