### PR TITLE
Update important note about Microsoft Lists in set-up-webinars.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7504.

@KarliStites could you kindly help here to confirm this information? Thanks!

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@KarliStites PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
@KarliStites PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
Closing this PR in favour of https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7852.

**Pull request closed without merging**
