### PR TITLE
Update sfb-server-updates.md

### PR DESCRIPTION
**Pull request by Ariantor**
Added SfB 2019 CU5 (macp3) release

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@Ariantor PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Review by Ariantor — COMMENTED** [review]
looks good

**Comment by Ariantor** [comment]
Manuela,
This is my first time merge. I tried to approve it but it is grayed out. How do I merge?  Sorry....

**Pull request closed without merging**
