### PR TITLE
Update Known-issues.md

### PR DESCRIPTION
**Pull request by cowitkow**
Older bug that was rejected. Probably an older item than https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/195092, but it seemed like one of the earlier ones confirming it

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@LolaJacobsen @chuckedmonson @tonysmit Can I merge this?

**Comment by kenwith** [comment]
@LolaJacobsen and ms.reveiwer @marcl looks OK to merge?

@cowitkow - thanks for adding this, will get confirmed and merged, much appreciated!

**Comment by MarcL** [comment]
Don't think you meant to tag me on this. 😄

**Comment by kenwith** [comment]
@MarcL - ahh yes, my mistake! The ms.reviewer is actually the Microsoft alias and not necessarily the GitHub alias. Sorry about that!

**Comment by MarcL** [comment]
No problem @kenwith. I was just wondering what PR I'd raised or commented on! Thanks. 👍

**Comment by kenwith** [comment]
@marcl@microsoft.com test

**Pull request merged**
