### PR TITLE
Update to healthcare templates documentation

### PR DESCRIPTION
**Pull request by aaronlai425**
Last minute change -- we are not releasing the associated patient app to GA, which means this template is on the back burner again for the foreseeable future @tonysmit

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@aaronlai425 Hi can you help by changing the author to kenwith, thanks!!

**Comment by aaronlai425** [comment]
Made the changes @scanum

**Comment by aaronlai425** [comment]
@scanum @tonysmit bump

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by aaronlai425** [comment]
@scanum  @tonysmit  pinging again

**Pull request merged**
