### PR TITLE
Moved  What are Calling Plans in Office 365 link

### PR DESCRIPTION
**Pull request by YuriySamorodov**

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@LolaJacobsen @tonysmit @chuckedmonson Can I merge this?

**Comment by kenwith** [comment]
@tonysmit -- haven't heard from others, is this something you would be able to help me understand and to approve to merge? I can send email to the reviewers if you aren't sure too. I am trying to get this closed out as it has been open 29 days.

**Comment by scanum** [comment]
@tonysmit Hi Tony, can this be merged?

**Comment by jambirk** [comment]
@kenwith I've taken a closer look, the link as "fixed" would point to a nonexistent file and probably break immediately. The link is now fixed as far as I can tell. seems to be an artifact of our recent reorg work.

**Pull request merged**
