### PR TITLE
Update sfb-server-updates.md

### PR DESCRIPTION
**Pull request by Ariantor**
Updated Lync CU10 HF2 and 2015 CU10

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
KB 4470124 was added but the KB is for Skype for Business 2019 updates (not Skype for Business 2015 updates). Can you have another look at this and update as needed?  Thanks.

**Comment by scanum** [comment]
@Ariantor Any updates on the above requests? Thanks!

@jambirk Hi James, I can have a freelancer look at this and add what @LanaChin has mentioned is missing.

**Comment by jambirk** [comment]
Closing this PR. @Ariantor let us know if it needs to be re-opened. I suspect this has fallen through a crack so long it's no longer relevant.

**Pull request closed without merging**
