### PR TITLE
Updating GCC High Support List

### PR DESCRIPTION
**Pull request by TokyoScarab**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3306

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen  PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@CarolynRowe @MicrosoftHeidi can you verify this PR for me?

**Comment by LolaJacobsen** [comment]
@David-Rosenthal - in Heidi's absence, could you verify this GCC info for us please?

**Pull request merged**
