### PR TITLE
Update manage-discovery-of-private-teams.md

### PR DESCRIPTION
**Pull request by borismilincic**
The command to change the discoverability is wrong:
Wrong: ShowInSearchAndSuggestions
Correct: ShowInTeamsSearchAndSuggestions

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@shpoddar - please review.

**Comment by LolaJacobsen** [comment]
OK per PM @shpoddar

**Pull request merged**
