### PR TITLE
adding method to create serv princip

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7480

fix current script and added a new one (tested in several tenants, the service principal is not there)

### CODE REVIEW

**Comment by get-itips** [comment]
@cichur Please review

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@cichur Cindy please review thanks

**Comment by scanum** [comment]
@cichur PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@MicrosoftHeidi or @tiburd 

> The author is not the technical reviewer, and may have no insight into technical changes to the product. The alias of the technical reviewer, which is listed in the article, is aravin.

Can you kindly mention aravin's GitHub alias here so he can review it and I can get this merged? Thanks!!

**Comment by get-itips** [comment]
@tiburd Can you help me to get this merged? Thank you

**Pull request merged**
