### PR TITLE
added clarification about groups created in admin center

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4806

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @scanum, for your information

Thank you

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
I'm checking with PM Kyle Blevins.

**Comment by LolaJacobsen** [comment]
From Kyle: "I can confirm the part about how to change visibility of a group in Outlook. I'm now aware of the state a group is in when created from the Teams Admin Center though, so can't confirm that part."

I'm checking with PM Roshin Ramesan.

**Comment by LolaJacobsen** [comment]
From PM Harsh Chandra: "Per @nomorephones we don't allow creation of groups from the Teams admin center. We only allow the creation of teams.

**Pull request merged**
