### PR TITLE
upload pictures

### PR DESCRIPTION
**Pull request by VLG17**
pictures needed to fix issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4503

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@CarolynRowe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CarolynRowe** [comment]
I need to follow up with the PM on this change.  We have numerous images using the same IP addresses.  We shouldn't change just one graphic.  For now, I'm going to close this PR, and will address in another PR.  Also, we usually only upload .png and visio files.  Why the .psd?   We  used Photoshop to fix this graphic?  We should be updating the Visio source file.

**Comment by CarolynRowe** [comment]
My apologies.  I realize I did not upload the Visio source to GitHub.  Probably a good idea to check with the author (me) about updating graphics in Direct Routing articles.  All changes need to go through the PM.  I will add the Visio source files.  Thanks for your help.

**Pull request closed without merging**
