### PR TITLE
Delete complimentary-dial-out-period.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/6419.

I think this article is misleading. Maybe we should delete it as it is more than 1 year after the benefit ended. What do you think?

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@tonysmit PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tonysmit** [comment]
@ruizoscar - Can you assist here? I don't know that we want to completely delete this topic. That is a call that needs to come from you.

**Comment by tonysmit** [comment]
I'm pinging a different PM to confirm this. Please hold.

**Comment by tiburd** [comment]
@dariomws 
Hi,
I'm closing this old PR for a couple reasons:

- It's old and there are file conflicts.
- The article that it's regarding, _complimentary-dial-out-period.md_, was updated in January.

However, it seems like a reasonable thing to bring to the author's/group's attention, so you are welcome to open a new PR. You're welcome to ping me to contact the author.

Thanks!

cc: @scanum

**Pull request closed without merging**
