### PR TITLE
Update set-up-holidays-in-teams.md

### PR DESCRIPTION
**Pull request by AlexanderHolmeset**
org wide settigns menu does not excist anymore

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8062

**Comment by scanum** [comment]
@CarolynRowe PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@tiburd Can you help get this reviewed and merged? Thank you!

**Pull request merged**
