### PR TITLE
Adding vendor name

### PR DESCRIPTION
**Pull request by get-itips**
@dstrome David, please kindly review.

closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7238

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by get-itips** [comment]
@Kateyanne can you help getting this approved and merged?

**Comment by dstrome** [comment]
Confirming change with product team.

**Pull request merged**
