### PR TITLE
Update Exchange-Teams-interact.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2481
Added info for Exchange-on-prem

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by lindspea** [comment]
> 
> 
> On a quick read am not sure this is the right place for that information (maybe line 59?)

Thanks Nicole, I think it must maybe stay there as the issue raiser talks about this section where it mentions AAD sync mentioned. "For Exchange On-Premises and teams integration, only AAD sync is mentioned as requirement. Please mention required license needs to be assigned for AAD Synced user". Let me know if you agree.

**Comment by nenonix** [comment]
I have not researched the issue so I dont have an opinion on how valid the point is -  my concern is that pasting the OP's comment, verbatim, into the table will not respect that the authors went to some trouble to use notes for extra information. (your call)

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
