### PR TITLE
Update sefautil-functionality.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #2718 - cmdlet correction (From Set-CsUserForwardingSettings  to Set-CsUserCallForwardingSettings).

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by MicrosoftHeidi** [comment]
Checking on this one.

**Comment by scanum** [comment]
@MicrosoftHeidi Hi Heidi, any updates on this?

**Comment by jambirk** [comment]
@microsoftheidi The command we're replacing here is not in the command ref, and the replacement is. Strongly suspect this should be approved, but it's your PR.

**Comment by scanum** [comment]
@MicrosoftHeidi PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
