### PR TITLE
Correcting Bulleted Point

### PR DESCRIPTION
**Pull request by TokyoScarab**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2154

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
I've asked the PM Vikramju to review this PR.

**Comment by scanum** [comment]
@LolaJacobsen Changes look correct. Could you please review and merge? Thanks!

**Comment by scanum** [comment]
@LolaJacobsen Changes look correct. Could you please review and merge? Thanks!

**Comment by wrooot** [comment]
Why is this change incorrect and is the current state correct with E5 repeated two times? Or is Microsoft 365 E5 Compliance not actually part of E5, but a separate add-on, just sharing a name? This is confusing, Microsoft. Maybe you should then add some disclaimer (add word add-on, pack, and also that it is used along with E1/E3 plan).

**Pull request closed without merging**
