### PR TITLE
Issue #2990

### PR DESCRIPTION
**Pull request by j0rt3g4**
Solving Issue with MCOPSTN5 and MCOPSTN6

### CODE REVIEW

**Comment by j0rt3g4** [comment]
Solving Issue #2990

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@Allan Carscaddon - please review.

**Comment by j0rt3g4** [comment]
Thank you @LolaJacobsen!  much appreciated! :)

**Comment by scanum** [comment]
@msmikedavis   Hi! Following up on this issue, please let me know if there is anything I can do to help!.

**Comment by LolaJacobsen** [comment]
I pinged both PMs again today.

**Comment by j0rt3g4** [comment]
@msmikedavis and should that not be on the text?

**Comment by msmikedavis** [comment]
What exists (calling it out as available only through VL) is the current and correct representation of fact.

**Pull request closed without merging**
