### PR TITLE
Update limits-specifications-teams.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4359
Added note.

### CODE REVIEW

**Comment by LolaJacobsen** [comment]
@David-Rosenthal please review.

**Comment by David-Rosenthal** [comment]
@LolaJacobsen I actually wasn't aware of this limit, but if this came from the owning team of this functionality I'm fine with this edit. Can you let me know where this info came from so I can follow-up after the fact to check on why this limit exists in GCC but nowhere else? Thanks!

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@LolaJacobsen PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LolaJacobsen** [comment]
@David-Rosenthal it came from this GitHub issue:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4359

**Pull request merged**
