### PR TITLE
Update Known-issues.md

### PR DESCRIPTION
**Pull request by cowitkow**
Regression with an associated work item (https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/358567)

### CODE REVIEW

**Comment by kenwith** [comment]
@cowitkow - hi Colin, is this ready to merge? I wasn't sure if it is still proposed or you have a sign off and ready to merge. Thanks.

**Comment by cowitkow** [comment]
Change to the document is proposed. The link above is a confirmation of the issue and the bug item associated with (hopefully) getting this fixed at some point

**Comment by kenwith** [comment]
@cowitkow - do you want me to merge now or wait for a go-head from you?

**Comment by cowitkow** [comment]
@kenwith Should be good to go now.  Thank you!

**Pull request merged**
