### PR TITLE
Update sfb-server-updates.md

### PR DESCRIPTION
**Pull request by Ariantor**
Adding releases in June and July of 2020

### CODE REVIEW

**Comment by Ariantor** [comment]
Hello folks,
Can we get the approval on this one asap?

Thanks,
Ari.-

**Comment by CarolynRowe** [comment]
GitHub shows I merged this 16 days ago. You're not seeing the changes?

**Comment by CarolynRowe** [comment]
The changes are already on the live site. I just checked. I'm assuming they've been there for 16 days.

**Comment by Ariantor** [comment]
HI Caroline,
This one is new, I just submitted a new PR. The PR number is 5877.

Thanks,
Ari.-

**Pull request merged**
