### PR TITLE
Update deploy-apps-microsoft-teams-landing-page.md

### PR DESCRIPTION
**Pull request by RomanMSFT**
Please consider the following edits...

### CODE REVIEW

**Review by JohanFreelancer9 — COMMENTED** [review]
@scanum, this is a request for additional information to be included, which should be done before I can do a copy edit. Thanks.

**Comment by dariomws** [comment]
Hi @RomanMSFT, thank you for your feedback.

Next time, please use the "Send feedback about this page" button instead of "Edit this document" to provide feedback/comments about the article.
"Edit this document" is to propose a direct update to the article.

Thanks!

**Comment by ashishguptaiitb** [comment]
Hi @RomanMSFT , pinged you internally on Teams to talk about this doc update request. Trying to understand what's required + what's available.

**Comment by ashishguptaiitb** [comment]
Hi @RomanMSFT , I am checking the exact answers with the PM team. I hope to have some answers next week. I shall make the doc updates as soon as I hear any answers.
Thanks for your patience.

**Comment by scanum** [comment]
Hi @RomanMSFT - Hope all is well. Wanted to check if there is an update here? Thanks.

**Comment by RomanMSFT** [comment]
Looks like the last action was on Ashish....

Hi @RomanMSFT<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRomanMSFT&data=05%7C01%7Cromanma%40microsoft.com%7C31409b4166cd4f58ff9208da8cf844f5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637977295182793299%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6eq2VsvPsx1fJ4M9A0j8YVJkc6eD9IRp1W1H40n5zcY%3D&reserved=0> , I am checking the exact answers with the PM team. I hope to have some answers next week. I shall make the doc updates as soon as I hear any answers.

**Comment by ashishguptaiitb** [comment]
Hi @RomanMSFT , I took it up internally with the PM owner. We are of a strong opinion that we should document the entire list.  (reference to "_all these shoudl be spelled out here._") 
Also, getting the license-wise mapping of exact apps will take ample effort to collect. What is the ROI of documenting this? Is this purely for info? Folks who have a particular license can already see the Core apps that are available to them. I believe that most customers won't be looking for a list of apps _available by default_ in the docs. 

Hence, my conclusion is to document a list of potential Core apps that are available by default. But not split the list based on licenses and not explicit provide details that the list is exhaustive/comprehensive. There may be a few more apps than documented that may be available and the customers can easily check it in their Teams client.

What do you think of this approach? Feedback is welcome, please.

CC @scanum

**Comment by ashishguptaiitb** [comment]
Any feedback on the approach, @RomanMSFT ?

**Comment by scanum** [comment]
Hi @RomanMSFT 
Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by ashishguptaiitb** [comment]
> `Hence, my conclusion is to document a list of potential Core apps that are available by default. But not split the list based on licenses and not explicit provide details that the list is exhaustive/comprehensive.`

We've done the above and the article is updated. Closing this PR.

**Pull request closed without merging**
