### PR TITLE
Update set-up-the-call-me-feature-for-your-users.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5222.

I've verified, and if the meeting organizer is not enabled for dial-out, the Phone audio option won't be available for everyone in the "Choose your video and audio options" screen. So you won't be able even to get the Call me option.

If the meeting organizer is enabled for dial-out, the Phone audio option will be available for everyone in the "Choose your video and audio options" screen. So you can get the Call me option.

Also applied more updates to the article:
- Duplicate IMPORTANT note.
- Added a note that we usually see on these articles.
- Updated picture.
- Updated some steps.

Something very important to note is that in this way we are also disabling **Dial in manually** option. I think it's not expected and we should report it to the PG.

Thank you!

### CODE REVIEW

**Comment by dariomws** [comment]
@cichur I think you can help to confirm and merge. Thank you!

**Comment by cichur** [comment]
HI @dario-ms
Just a heads up, the image files can be no larger than 650px. I noticed that one file is 750px. Will you resize the images? Thank you, Cindy

**Comment by dariopb** [comment]
@dariomws I think this was for you: "Just a heads up, the image files can be no larger than 650px. I noticed that one file is 750px. Will you resize the images? Thank you, Cindy"

**Comment by cichur** [comment]
HI @dariomws, It looks like someone is committing new image files. I noticed that some of the new files are larger than 650px. I commented that the files need to be 650px or smaller. Cindy

**Comment by dariomws** [comment]
@cichur done!

**Pull request merged**
