### PR TITLE
add info about apps pinning precedence

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4481

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by LolaJacobsen** [comment]
@get2chhavi please review this PR and let me know if it's OK to merge

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by LanaChin** [comment]
Pinged PM and removed @get2chhavi from assignees.

**Comment by LanaChin** [comment]
Made some minor text edits and merged.

**Pull request merged**
