### PR TITLE
Update teams-for-vdi.md

### PR DESCRIPTION
**Pull request by datarchitect**
ALLUSERS switch seems to be wrong for per-user setup.

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by datarchitect** [comment]
Does not seem to be updated in live document yet.

**Comment by LanaChin** [comment]
Hi @datarchitect  - Thanks for your input. I reached out to the product team and for installing via the MSI using msiexec, it's desirable to use ALLUSERS=1, regardless of whether it's a per-user or per-machine installation, and whether it's a VDI or non-VDI environment. This is because this allows users with admin credentials to easily uninstall Teams because the Teams Machine-Wide Installer entry is listed in Control Panel and in Windows Settings.

**Pull request closed without merging**
