### PR TITLE
ApplicationId missing from examples

### PR DESCRIPTION
**Pull request by leeford**
ApplicationId is required to create Hybrid Application Endpoints (used to specify type - Call Queue or Auto Attendant).

### CODE REVIEW

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@jambirk PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@jambirk Following up on this PR, it has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by jambirk** [comment]
This isn't necessary at all. Assigning a resource account to a service type is handled online, not in powershell. Where did this change come from?

**Comment by leeford** [comment]
Hi,

This has come from step 3 on this page - "Create an on-premises resource account by running the New-CsHybridApplicationEndpoint cmdlet for each Phone System service, and give each one a name, sip address, and so on."

"New-CsHybridApplicationEndpoint" cannot be run without the -ApplicationId paramter as far as I can see?

**Comment by jambirk** [comment]
I don't believe that's true. You should be able to create the resource account and then set Application ID later. @waseemhashem please confirm.

**Comment by waseemhashem** [comment]
That is correct, you can set the application ID later using Set-CsHybridApplicationEndpoint

**Pull request closed without merging**
