### PR TITLE
Add volume params to xml-config-file.md

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/8740.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@cazawideh PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by cazawideh** [comment]
@scanum please have @dstrome review, he owns this area now

**Comment by dariomws** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@dstrome PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request closed without merging**
