### PR TITLE
Update devices-usb-devices.md

### PR DESCRIPTION
**Pull request by lindspea**
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/2050
Amended vendor name from Sennheiser 65T to Evolve 65T

### CODE REVIEW

**Comment by scanum** [comment]
@jambirk Hi James, changes look correct. Could you please confirm and merge? Thanks!

**Comment by jambirk** [comment]
@scanum  and @lindspea 
Please don't implement suggestions or approve updates to anything in that /certification/ folder without  approval from @dougand-MSFT or @dianavank 

Device certification claims are bordering on legal contracts, this is something only the PMs should be updating.

**Comment by lindspea** [comment]
Noted, thanks James.
[image: Picture]

**Comment by dougand-MSFT** [comment]
approved for changing vendor name to Jabra on the product Evolve 65t.

**Pull request merged**
