### PR TITLE
Added Edgemarc to Ribbon SBCs list

### PR DESCRIPTION
**Pull request by FilippSe**
Added Edgemarc series to Ribbon SBCs list and unified version numbers for Ribbon SBCs

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by CarolynRowe** [comment]
@JohanFreelancer9  @scanum 
There are conflicts in this branch that I do not know how to resolve.  Should we close this PR and ask the submitter to resubmit?

**Comment by JohanFreelancer9** [comment]
@scanum Copy is fine but please respond to Carolyn's question.

**Comment by CarolynRowe** [comment]
I am temporarily closing this PR until we understand and resolve the conflicts.  I am following up with Filipp.

**Pull request closed without merging**
