### PR TITLE
Spelling corretion - "Unites" -> "United"

### PR DESCRIPTION
**Pull request by frankshearar**

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@Lovina-Saldanha PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@Lovina-Saldanha PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by scanum** [comment]
@Lovina-Saldanha PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by CarolynRowe** [comment]
Fixed.  Closing...

**Pull request closed without merging**
