### PR TITLE
Update teams-client-update.md

### PR DESCRIPTION
**Pull request by RomanMSFT**
Hoping to get clarification on this behavior...and doc to match expected behavior...

### CODE REVIEW

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks

**Review by JohanFreelancer9 — COMMENTED** [review]
@scanum - This comment needs clarification and the topic updated by the product team/doc owner before I can do a copy review. Thanks.

**Comment by JohanFreelancer9** [comment]
@scanum - could you please assist to get this PR moving forward? Many thanks.

**Comment by scanum** [comment]
@dariomws Could you please help with this issue>? Thanks!

**Comment by dariomws** [comment]
@scanum I agree with @RomanMSFT. I tested it and if you try to open a more than 3-month-old version:
image

I'm removing that sentence because the following one is true:
"Users on Teams desktop clients that are more than three months old will see a blocking page that gives the options to update now, reach out to their IT admin, or continue to Teams on the web."

Please close this PR.

**Comment by RomanMSFT** [comment]
Thanks all..

**Comment by RomanMSFT** [comment]
All,

Still seeing "Desktop client versions that are more than three months old upon first install and/or first run of Teams have a 28-day grace period before encountering the above-mentioned ..."

Seems like it should be less than 3 months old (or actually older than the version in MC245996 ).

I think this means the PR hasn't gone live yet in the doc?

-R

From: Roman Maddox
Sent: Tuesday, May 18, 2021 10:31 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>; MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Update teams-client-update.md (#7098)

Thanks all..

**Comment by dariomws** [comment]
My Pull Requests is still pending approval. Once it's approved, you'll see the update on docs.microsoft.com in 24 hours approximately.

Thanks!

**Comment by RomanMSFT** [comment]
Ok, thanks....any way to get notified when the 24 hr clock starts?

**Comment by dariomws** [comment]
Yes, subscribe to the PR's notifications:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/7218

**Comment by RomanMSFT** [comment]
Got it, thx

**Pull request closed without merging**
