### PR TITLE
Update add-or-remove-an-emergency-address-for-your-organization.md

### PR DESCRIPTION
**Pull request by CarlosFarrica**
Added troubleshooting information

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@LolaJacobsen @tonysmit Can I merge this?

**Comment by AndreaBarr** [comment]
@LolaJacobsen @tonysmit Can I merge this?

**Comment by tonysmit** [comment]
Yes, however there are a couple editorial changes.

Should be Office 365
Don't cap Emergency Address
Should not be "was not" should be wasn't.

Please just review it and make other editorial changes.

Thanks, Tony
________________________________

**Comment by kenwith** [comment]
@AndreaBarr - can you make the edits Tony suggested?

**Comment by AndreaBarr** [comment]
@kenwith Yes I can do this

**Comment by kenwith** [comment]
@AndreaBarr - perfect, you can click on the "Files Changed" and then click the pencil icon to edit this PR directly. Then merge it directly to patch-3 and then merge to master. Let me know any questions.

**Pull request merged**
