### PR TITLE
Update Known-issues.md

### PR DESCRIPTION
**Pull request by cowitkow**
Known issue added. See (https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/211743) and (https://icm.ad.msft.net/imp/v3/incidents/details/67420691/home) for PG confirmation

### CODE REVIEW

**Comment by tonysmit** [comment]
@cowitkow - Are you an internal MS employee?

**Comment by cowitkow** [comment]
Yes, I am. @George Vordenbaum<mailto:georgev@microsoft.com> is my manager, if needed.

Colin Witkowski

Support Escalation Engineer
NA SFBO / Microsoft Teams
Customer Services and Support

Office: +1 (469) 775-2259 x2259
Email: colin.witkowski@microsoft.com
Working hours: Monday - Friday | 9am - 6pm CST

[Microsoft Logo]
Team Manager | George Vordenbaum (georgev@microsoft.com<mailto:georgev@microsoft.com>) +1 (469) 775-4543

**Comment by cowitkow** [comment]
For this one? See Derek Daniels (dedaniel). Confirmed original bug item rejected and pushed for getting this documented publicly.

**Comment by tonysmit** [comment]
@kenwith  Hey can you not push my stuff live until I verify the information please? I had another thread with him and PM to confirm this. Thanks, Tony

**Comment by kenwith** [comment]
@tonysmit - oh sorry thought it was confirmed with the comment. I can revert it.

**Comment by kenwith** [comment]
@tonysmit - I reverted.. when you ready to merge again you can just merge this one.. it reverts the revert: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/165 

Sorry about that.

**Pull request merged**
