### PR TITLE
replaced sentence to Known Issues

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report  #5903.  So I replaced  **Support Teams in your organization**  replaced by **Known Issues**

also, I formatted this article,  removed the gap between certain lines 
Added the gap between certain lines

### CODE REVIEW

**Comment by scanum** [comment]
****Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by scanum** [comment]
@LanaChin PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by RAJU2529** [comment]
@scanum . I am getting This branch has conflicts that must be resolved.

**Comment by LanaChin** [comment]
Microsoft Teams Rooms. Assigning to David.

**Comment by dstrome** [comment]
Thank you for taking the time to contribute to our content. I unfortunately am unable to accept these changes because the structure of the table of contents is tightly controlled.

**Pull request closed without merging**
